/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	H:/AllProject/Tang/work-ritter_soc0.4/project/al_ip/sd_card.v
 ** Date	:	2022 02 12
 ** TD version	:	5.0.38657
\************************************************************/

`timescale 1ns/1ns
module SD_CARD
#(
    parameter DEVICE = "EG4" // "AL3"  "EF2"  "EF3"  "EG4"  "PH1"
)
(
    input   wire        clk,
    input   wire        rst,
    // sd io
    output  wire        sd_sck,
    inout   wire        sd_cmd,
    inout   wire [3:0]  sd_dat,
    // data read
    input   wire        ren,
    input   wire [31:0] raddr,
    output  wire        bken,
    output  wire [7:0]  rdata,
    // data write
    input   wire        wen,
    input   wire [31:0] waddr,
    output  wire        rden,
    input   wire [7:0]  wdata,
    // busy
    output  wire        busy
);
`pragma protect begin_protected
`pragma protect version = 1
`pragma protect encrypt_agent = "Anlogic"
`pragma protect encrypt_agent_info = "Anlogic Encryption Tool anlogic_2019"
`pragma protect key_keyowner = "Anlogic", key_keyname = "anlogic-rsa-006"
`pragma protect key_method = "rsa"
`pragma protect encoding = (enctype = "BASE64", line_length = 64, bytes = 128)
`pragma protect key_block
ftugFfyxYKjqZnBe0oWQhmo9zkO++UJao1xCl6/J0eKxwBWOWCq8jvS1qELfkhrx
P6cZEkGdk9U8mq3Kp/Z2Wf2clEW2zrcjgcQKFJya1ana1hRGbMpDZsZtiFSOAunN
sw7LvCr52jIQqqD0YgQy4hHEN/Uw1/6FVs2p0b3+2aY=
`pragma protect key_keyowner = "Cadence Design Systems.", key_keyname = "CDS_RSA_KEY_VER_1"
`pragma protect key_method = "rsa"
`pragma protect encoding = (enctype = "BASE64", line_length = 64, bytes = 256)
`pragma protect key_block
KDrC9tNhvSjbMaodzt/vxWPokXZb7FD4PQMESCv1GFA3XjTqRjXZttgyEa5ja1AP
ov44jUJjWxMaTKB6Q7xiuKZkQL1Rewp8GmBCTMYT0BHdpFLNkhXVT7YtwGkhR//e
Wr/M1kWa5TrX0gewbDMZVQappSYmjW0fgf4QWXtl/p15AUAP3tsujU7FDCWtaM3v
UWUoZ/5EJDJ0f8BiVBKQNqTGqsiu5RDRiLB5uGY9aSlxXSvUxcjTp37xqlFJxVX9
q0sUL5bQ5UN8D9igAW9msHw3IJ6xUhiZQG4cKZ7pPJ7YKzKWlG/8QCDoulYpl1B1
+bLOo7ZpOTwvhebVypnNlg==
`pragma protect key_keyowner = "Mentor Graphics Corporation", key_keyname = "MGC-VERIF-SIM-RSA-1"
`pragma protect key_method = "rsa"
`pragma protect encoding = (enctype = "BASE64", line_length = 64, bytes = 128)
`pragma protect key_block
C24j5DYQkv5i2zeMHgaIxe1RGYpM5rZ4ln5w6cB620b+L8yHunENFf8bVb9sOfar
zHw4OTjLv6M6MuFeRfnRhRhtJO/R4RMECRee0Fj+ehKDckcP7AyqlHokKKuUVi05
cZvUrQ805CKOzGbVo44lns6A3eNPscZJX+TQQ181saI=
`pragma protect key_keyowner = "Mentor Graphics Corporation", key_keyname = "MGC-VERIF-SIM-RSA-2"
`pragma protect key_method = "rsa"
`pragma protect encoding = (enctype = "BASE64", line_length = 64, bytes = 256)
`pragma protect key_block
DF73z+7k/gwm9BvaMGHRX/Q9qIxmQCb0O6rvzx+dbaXI5Sl6R8qEk7t8uqPYYUX5
d7nvAXLCzbmxrxXpX3fbX2q1OTQyTmvzul6R94cD2NbCFP9bCt4TS3PGn4od9UIs
dT2yNZD1kUO1Wt5VTGWXSKgRRfliS9sgxCz1+QV/fLXb4ssPg2JbnKk2fOjdefGz
nA39uFuASy8l9zek4h0T7JzYO0iRn2vREJfy43ZGnJgt/H+8y9XD0L4SA7DpC+rX
Vy5LVlihLY9p0zh4Xulza+k/4r1ditHLTkYvp1DmZ4kCnLqxvbQ2Q8ersil68Vyw
IDASX+NRfc/fUqOIam1iLQ==
`pragma protect key_keyowner = "Synopsys", key_keyname = "SNPS-VCS-RSA-2"
`pragma protect key_method = "rsa"
`pragma protect encoding = (enctype = "BASE64", line_length = 64, bytes = 128)
`pragma protect key_block
Em3gKojDM4oj8AEbwsaMOoHVSBzuSEkmHw1Id7eEfj9MRlnRYv0d1oqW+SWZ1szq
4q2ArWFjrKGS62x3JwjMnLkxl58QSRP8Ro7PxXafB1oZ3H6sKfoW0XB20z0eBCfY
ka9BMilsa9aFI2RsCWvPGhqNAWDlMqIi3CqEO36YyIU=
`pragma protect data_method = "AES128-CBC"
`pragma protect encoding = (enctype = "BASE64", line_length = 64, bytes = 3824)
`pragma protect data_block
aktHWGF3UWxoSkt3ZjJWd1BNm3nXTkiWfu+AMumOleTzWWDjMCP0uDRHP3v+3GTP
oQ9ygRUJ+IPaZrDtTIfTbFz48b1HNnuifSxOasoLe95Pj7PEo9mS+3R7ERPnIqIR
fBIGeOGF6WdXOVP12cLmvyK59oYOCo+Ua/VtqbnPX3muuqRQYe+1/oVcOmeuohWw
yjluTKRNm706EAJ64g4fbuPBgxm0HIk/I87KPp1+73HC0tCx3Xi0SAIVNpsBVxDa
9pako5Xr5AmoJYU80PpaTt+on7MtbVB1y5hhpIUa9REGpIwr4L3IgI9rzYzBPi15
cAFW5Y+RbKbaTt6Rt8Mqj+jncHnmCYQjXBHodUQjt+52jfObSaqxbvu6AIl3urnk
SNCoV4UFE7EujQq/UMVYM8McNnarEtSKa7W16KV0/6bUCVfly3G13XDN0gvGOPkq
XcvA9BWD+z6LZp3cpw73jOaNUYqqfcjktygHGq4m1oEtPtProcK/tfO6pwvnpiP4
k9TLKQQQImvDmLxLtFvcahEUO7l745ajn2DU8TIx2TJpgOO7nzQ4l7L8IaUSNZdz
BdFsZIdwA6BA1eNEbqyDyo5E7UWmTKspVwaM3u+q/rV4FkOFj3e0q5p7AyVuTb7D
bGaeT2Aoh10EoxKRYuwX4gi1Qy72Dz8FyOHlx4l4pCkJHZfe4KJPprZHOi+am/SI
HKhjgc/SBDiTnCALHOQImvsifKpHkLNTfl5/oZ+1g+E2BNVEpQyf03rc2XB+aOxs
SPeXhiY/XJ/fkfSBVSodDqkyCCk7TM46N5f51JDWmdGmVqiUHEs4AUbO+TY26ZYD
D5hBu6cTtTT4ZmBRa1lA8AsQhqzBwKuxl//lcugcM9yAH6OSTp8zHNTUmGG+mxO3
GnWsZOrQ8v1u5e0SAMQuVbjCA7Ac2s+zIjgfcrz1Js9AHxEn4tgOadqjVPfIY0Zp
jdV6D7/7NZkCLQSGsARZETDAaMGMgbpVAYSXPltIc++0w/97VyabC2+CQCz8RpFe
EwIAFecdRVhnG5ONz4X68FDz/18R0jxbp3UcGok5wiuQguwhUwylw4F8L4CPy+CG
JMRZrOCbHHxbwg8FfZIkpxlc/ZxGfFJ2bSDpIvx1tb3SrTx7J890FNaQJG554qJ/
nJ/9pOBlE9aQeNNDhBDgaUq8DT43OiKh5ofioXDTjTY1d6ID8Ojik7xRUoePtpci
9Ba0b7e6QmvPRIV1Hlvg1kv55Ed+TnQPOdJHkuXK2BBE7G4EbULne0FGNCs4b5d9
HBBEoSVmrCwcZbuN25KDHOheDQU2qp7OCpGbl3kMcxu0BPrTwPl89/ErnIcvYxEr
LdVDubJwuQqwtsC577iA2rYalqpbxzlQ1rYh6Lz301tcCV4RoEAqpz7Y4ztbDT3z
5dfh17qz4fam8tblpguDmcY2L2GjOu+Ey+sA+b1pjnWMKNoRdbaoGaNfZaHu/ew2
hMFrmVEaNjHexOC30dbWvEvPH6shzXyRbKVa4pauHlD4yMLEOhAM3j5ih595KDPb
5mW242OszeNinkcY9MYraRqONUfVblKtJfCnlZ9cpbf9ldUIEq+6gPnQEkYC+z1t
pZrEqPfml+oDvjZ5tkEuyXhNFTX8qLUmtRup4SBtz5yBdxLusDqX+d6F5OeccMB+
ES169WoXmlWDAeEocxFeCXsuWuZ9mcSVXKtUl0A+AKs06BR/BlfckPePx3EXZJPX
8dDL5vy4h1L+F6cgnDXOfW/Xmv0ME9oi0HZDT3O9s+J63MwDU1WFG3QFAgSxhBys
OYf+23UPz2Plzc7xPQC7e6b3uKHxiheN7mPSYcZ78pw2/X99GSTzUd9dVFOurHzb
w7ywysAz0FdsoaeDr+euuWf1KKbHFn0MZIb8Ye0yfWMenwxnUbSiLp4A9jiq3rx3
U93qNMKmieGoLtLxFV+nS8hNmOiMZWKQp281ESKKH/t1RNF2aP0kijJm4a3bKSBB
ZjpBZtDcD4Mu7fvu0AJ/E7qxjGJtSOWRTV8wtLGV9B2dgzk6VJ77B45hmOFe4lfS
WmGU4ErGkuMhPwbyLhxgTZtbwO51BPoiXzjqEXS9rE19FaFC3hrsoyYt1aKDl4IH
U13SxPVo1Z9qZGyXR6aygo8eXbo+Ad99R20bPq484u89+4iL/NNyIeTJmcbHrOTb
FP21sfAsg91K2pBf6getxJFognOMFCDUVoJefxw6GlBk1125SKM1iI9ZcjQ+dxGy
WKpsBFH6GkxzzD3CKAockA0qCKx9cCOys5w06SLGB6b34mNstAcIfZOeY5c/RnG2
jiPc+OXR+VdYlHf7GT0pcpdz59nVHdALTXLbYQKZXdi479Pu14LNADCsGemRh+qh
t+I37/PVzD82l/aZ/SuZPBU48aZWNqDMToIEiiURGn/av4NuLqiVKViqSoQ4zqlE
3V0dzniOEXfOWalZuDOXrkMFN5Ey62Mu+QnITmmzU6T2iQd42AJt/QRVx49fMMQ2
EMUPZLVOlmTaFOwnTZPM65N8Yza0Vn0W9kSoAFP2wkVY9MqMxbJNeQJbSXQq64Lq
Scoy36gZYgcsgZBTWPp5YqXY5gYwwVEm4xZtNyrjIySWJQH60Q3pbsV/ZH8KlV4U
o9dmCpssgybxoo55Wk1kbBBptOpw3cO9Bo6zgB+Ad7WEeM/b8JJiH9f7kRrAAHJD
YsskWAeGFHWmwdfuBVg0CTsJtTgeybNVbKZaNJvvbsxCbGeTIkWRl4Kw732SZjt3
vCFPFiWjw6S999XsGp2bERqSiKh5vVnn7Ud8EpH7ZixnML20Z1i0p2ygaoaTpPw2
I0tTz1Gfl4DPiIw/4Ed97v7VbySwia8k/0TD0ldi9smRnQRlMyXaNn+2ZopbJ8RX
CkUOJUwPuMugfnTUkJbkJrWeeudhPT8zwfMnGyXwPMABqQAKT1sjWLgq2LcupZ+r
IH1M2BItVC/R739QXhoLBvCb6A2TlxuMwfBuFnOD1o94q08wLZuc9YIamF7XKQo3
jGmsC27Cuwu9NWZEnI9JXfcfgJH/6zIw5WtTfQmOlncCshZ3WFDdKxcPktHEgKw1
QcIOXXvxikKJRfcTYljfN1mj6ZzYcFfOlQSZvyT2yd6m6M7b5gQRvbo/O/uw3xhr
X6fJZlpj2lqtWAAKmkZZYlys5HeOwZLY+onYMTFiekklDv1O/58oKwKbYbV6XQWg
YY/0mBtCgYFENvu3cAfK+2PR4PDR8vcXXTqBosY2YxRqcfp+x+0PBJZck8cmQqCb
fEvZseoZ3bxSDXOTaKGOhsGm6gnSAcsf3sT+GXz/QmcSawKkncAFJPfAGsTnpOD4
G9mVlMGK9PfZKjkiR4qB0locl4Kuyte1WyGUDk87PWwS3dNYiqak4bxltQ9/FZK0
zU6rRgMq2cJjXO3nG7qVFOkliuY1jCkSaIb0ZfD6kavpVCAi/rU0iZjKTDNIUFP1
Ba7hYzIleTR2dUTthRNvpLb/BBpbNIbb/Zrvrz6FgAnQEuufVqdKXRThmmLc/RkC
DUEt+7DVwYO8oEf/D6Z6YIxDOhIqmxY/eb5o6Qnd+lH2nA07IxtuT9/VYoXSXoj3
csA7Hjgi1tpSJoOXHq45Gql+UC26ZkPoPI+evt2Kh7tb5tQ8viSFdpWChanUlbS3
sMHRCkxVJiCKg1FtnSjYgeswpsaamPvyGxEMKudGZqjWjmDrChZNCOjC8hybxF8j
/ZKzojtKUffrowlg0diRuRQIoOlhkWSpGhDGLw5ktH+4Khq/lg+DKd/UvOJHLhXC
7CIBRndvgQDkn2rEMyxFWIIig1OhFQ4aKlutqQgzMtPCut44astLJgzPonAJBYER
Nk4Xo/SiOEfZDG5Z31+W0gy/dWyjhB277dkVEvEZkU8+Ghyk7gmLrrhmxOgX0eIK
6vl0+jARSOMLkLngFT/5Hi1XO3no2JppmSxmTnHOmK2/VKBcIwTeFYBSIYISI/sO
MYfqWJAAns4T5jCgOJIL5kXRWjIaOtA4EIy8vYEl71cS2F8PYuS0867nZo4Xb4+V
/s453SDaBRoX0OcPwXt02ahScCUk75xA1XsnfIy7I4oBJu+TeasUDnEvvshSxAm4
wNJXJTMtBQ5k+KO8z6IdBt54sgDEWW9CjTptX1v9HGMrffzASDB6XJZlWGaIawa1
ooMGaTa/Ptmi++qrv+Lj/sWILIrFiKNPvqtcMHv9w0ERwrHFysE+DzbriOPfFoN+
EO/Gx1TN31YAimeSQSce4vZ7ohpcGPiCNlEIIsrYSaItKXBB0bzi1ToVWralyMSe
OXhPznLo/g6U25hBRN4wpxiiAIgp3bt8az5kKZqfNHIzFboR6bmFnvmQkwe3nvMr
kL5UNHN7mvn/FHvLfdI18AR6RcStcC32pOqO3BPHc62zYooX8tygvPaJtFGq2CXx
+TI6lkMd8QlSH2S+aHwb/6EdhMiEXz6GQit6wqTKaDSc9hpCY2E9JwGKbl99B4Jv
a0x5pBnZMCrXUIhVHwdp6C+6tw/EVL4wWWoaLsCNjU+0tKR8hlxyhtAjBXxbM0Zd
eDUd0HttacKJFbW8qw2z3LakQ004TDTkYQSp5//8xfCzCeG9uMPa8VqgLt12oipl
saYdtI/2QY9ml3TK+KCpnua3cs4sihoWdXgw3ezJLDocrZkuNKr2/aV/iljSeb7D
Y/AA8sMK03sCK6NcJfpsnau+B0KMGq1zZIKjsPmBXQ2mera3rdLcZbS7VKAp6jR+
vv3Q8GPmOYWJufLQE8noitRIU3btx3qV7Z9Qi3Y7JSZMM4mEW3jy7t5Qo9f7QNbQ
qFBYi+JxNZjGCsCn5oMmnOohaqzUZrl/oA4sFtv9HVEA7RKfOJ831BEn1txgaCm2
wDVEJbeHphh2ahCQbiZlqGV6WdT5zKiACC+z3BxxJAwTCxOnluu4DQVpOOG0YhKa
m8d0adq0C2K0Oe/OeSRCzbn3gHn1X54I4QsJ+QyWCMxWiGmbYHN4gYUNBvic5dU8
BVzMpAJPb7MxgIUEqpC/RpTZOwDQbe0ryGJ+4tvAzLuAN5eFUlZDW0UtQreO5Hq9
961XjqCqSW07lslVuTF8molq+GZ7m6rMpTcIcv1qnz4=
`pragma protect end_protected
endmodule
module sd_init
#(
    parameter DEVICE = "AL3" // "AL3"  "EF2"  "EF3"  "EG4"  "PH1"
)
(
    input   wire        clk,
    input   wire        rst,
    // sd io
    output  reg         sd_sck,
    output  reg         sd_cmd,
    output  wire [3:0]  sd_dat,
    output  wire        sd_dir,
    input   wire        sd_ack,
    // done
    output  reg         busy
);
`pragma protect begin_protected
`pragma protect version = 1
`pragma protect encrypt_agent = "Anlogic"
`pragma protect encrypt_agent_info = "Anlogic Encryption Tool anlogic_2019"
`pragma protect key_keyowner = "Anlogic", key_keyname = "anlogic-rsa-006"
`pragma protect key_method = "rsa"
`pragma protect encoding = (enctype = "BASE64", line_length = 64, bytes = 128)
`pragma protect key_block
GjrGZKSb0Pa2Tw76aU20zT5p5DVp2UUc7+P5TwTPC23/zqjR2N6JZWcA3jT7R5K0
EEnXPXwjSHDzn8H8/DBGJ+ke2NJJuBdr1hTSjt1MOaqXb19odeG2x4zmo5+J3RKE
RjyUnQPpSsIXJbnlGNIzRgJ+gXLUGbjNlmiYt3WT1rc=
`pragma protect key_keyowner = "Cadence Design Systems.", key_keyname = "CDS_RSA_KEY_VER_1"
`pragma protect key_method = "rsa"
`pragma protect encoding = (enctype = "BASE64", line_length = 64, bytes = 256)
`pragma protect key_block
cokrwtV63qFpiDW9/hwgbyg0gDAJTu6RWDHKUyCTVAniuaFTV55Xx8U0+vA8QaT+
pmLEQdV4tX73dKP0wwYC7QrAewit4k/w+xepcS5i8bamZsKCJEJGOpYns2q2oFBN
sUOydUPeQbl0IfnmrLMHL80C8aCCWETUTlNsnJKDCuMnHZT+Sr5q4i1cLYAnAXEr
UmQV3U8BOdutQM6N/lieTlfbXKoKxeM2MWEAyksKc0Rbovea9GLKXQUYIFrFlqET
yClyQVtY/EhMB4h+mb7E7idXT9+uy0kuYdtznnJaOYyr/7GRARbQtr9saJ25TuWJ
zH6dcDXa4YbY7u/YLRChYQ==
`pragma protect key_keyowner = "Mentor Graphics Corporation", key_keyname = "MGC-VERIF-SIM-RSA-1"
`pragma protect key_method = "rsa"
`pragma protect encoding = (enctype = "BASE64", line_length = 64, bytes = 128)
`pragma protect key_block
j2lwjmjjSbgUPQa5CK5YEZBODAD4lE/50lHy+IOdPz1QouR95C+VcFBJ9XIEHscY
bY71OHC1Zduqk9Ac2kKBnrJfd/MAQfxVpSlwESakf8puWGbzE3zBX6P8NIYKOuC+
e4S9ExKkUGg4QNlmSpjNOjKPuAXFlpvR4mDYKnEPfxo=
`pragma protect key_keyowner = "Mentor Graphics Corporation", key_keyname = "MGC-VERIF-SIM-RSA-2"
`pragma protect key_method = "rsa"
`pragma protect encoding = (enctype = "BASE64", line_length = 64, bytes = 256)
`pragma protect key_block
pSDP1dNcF7JVloWo/IPIawRf/VbTCXh3lr2kpkCusURRHdGQ009EpKOh/nY/+FqV
n09cFhfJpdjOyYJChqDg08fHPncHZkpc+PMx6i7st8YseQLuw7xjO2sK9vx8q+S5
a3XY4Ddrg0iCkSUeBbUrxt7KIFiLGoldiIpHrY68x4G98SENbQUXUjMxZ6djKHD6
OCyQojjaKIm9h6Kwnn9wl7Qd8hM+KAxgDeN1JAc0Sz1B75z7bO6NiIj0MOvjk3It
er1G14hI7hMWUMh/tvg/a+bmn9F8XZpyI15ADeqihH1oNZM8BiEjzzLRUKKUBhkG
9lOKeLaMgw2oeOcKpFMgtA==
`pragma protect key_keyowner = "Synopsys", key_keyname = "SNPS-VCS-RSA-2"
`pragma protect key_method = "rsa"
`pragma protect encoding = (enctype = "BASE64", line_length = 64, bytes = 128)
`pragma protect key_block
HBZzGoQDkT5GkvQW9ziwmyvv0wTSWAeZWL/AT5WlRrDm0iNRaIHaLq5iNCc6SVVH
VTT13fWdp2VpfLpd+Z0Mg2vhAOVqFNbkAbUvwJPQHhAmFUc6QEgJIPKsmA6B5zYl
1G2K8sci9IWRS5CMtVf8nnfJwWrEOtSKvLh4iCag3no=
`pragma protect data_method = "AES128-CBC"
`pragma protect encoding = (enctype = "BASE64", line_length = 64, bytes = 3968)
`pragma protect data_block
ZjR0c3lHRWsxNHd6N2twdPWCxUn5H/OSEVXFdg6eRFCpHZBVDBCyt8YArUF/Gg1P
fcG4trmWWLGg+sfrjFwn+wcVkooejCHLqWXWqGUjMMAoplNL+WQlJJoSOojRqfNQ
TXGjhNNFfBaid6zL7CswxXKqM8Y/akXVXTO7oKeD0xnev5QUbeQ0noZuYZG79Mvg
PvfDrhIyHueZ8HRBg4vhP+gZU4p91FlSBjlUD8iiw+1nPM3VBe9YWqeKBYTDpZ5a
OWZO+znrIBThsTfAkz5z0gMVWCXxQEpCDTIVuLXOwKAmliA0XjK1IgkOdn7C6ns1
xQtuaDm8oY39gBXYzrsci1Av9h148NZNNwP0NAPmTtqA97AKaKj1g4TPpaWmVHan
ljCTXcj+Vlb6OKqPkxQWvn97aXJq7FAbxK0WSajHKkLaK9GuRhvyZZXYMmHSH0Iy
8w4uYUfc6rGuBiiyV1/IdQK+Zwf08uxiL4u8hSbTgO7MYGolechOaHWXKWxP8XxF
R+0X5/vILxLH88A3fVTIlICvTHUSczVT3BiIg3zj43VoNs3Z63fxNefUvv++9lCz
XKHXeoeWLZ92EXuAvCJCXZT9zXFe1nR5bwErtSNpZFiPW7BvccKfZ7o2wHPBjhD9
crtyH9mHw+697TfEb91tSd5/52FMKlo7S956fO74tplBPm8rm7mr9lJI8vXBtN5U
yQCtlVhITd/GaIx9QqIhfQNc3BjdNIw+3Gw/g2sUnkRlEVB8KpZ8d/03GmZVbY83
1V82rsu9/PbF7Jwiq0J6WgnOebN9doooPIaHrgOVDyK6qAIMxrYyBfSaEXd+PvAV
laWE0OjWldubL6xCFLG1W4REiPsX0BRJEIoBYMSWPTgIu4ZpOXDRCzQui2UBTvEd
0zDjLAgU0OIVv3+Sr5cwm8jj35qENYU3t1+QU+kmhXQ2j9GQthMJpGviEMDkohMx
TvEjiIMWb2lLtW/NhXOLXyjD+gTvSX50ipjCjK+mi0SuKwpHV0jvBaTt+PR18Jah
u2XBEdjrQKjaBqIuEHm1lPTmKzwGrvIkhbtIM4S6sMPK29JmT4IK6jAe1qBaIH5M
r3oThv5LMHQLOnEN4X9CgaFGJ856VEuRrbeoVF8V7Fvzb4p/g6NcSOglGXP4Gi+C
s7CwVkuvqhFo5qhEre3GGWn0lCrwIKVkIr9XYdH09h6bs8cyoHi6QLgHJIsNeX84
AvlsSKHefO90czBtb24KkIr2JZTYIwxzf8TQqHKYRy/fqqfrVa92aDBFdoziMuLW
1Jz8pLKrjNMHweU0gwlNUBrcxQgem2pv3dmGaVDRqe5GXf1fQSdpnf/47+3F2v/y
gJp9494nj/TPwNZwhJ52tk833LF0F4c/t+VPEhUMqOUnGBp+3tbpdpfYv8h7L1X6
JdmuwpONTiIbTUOXfVDpAzhsM5RyAS9TRochh/jqp7Y4ruDlpAwsRrjVdF6viDgh
hDwXP9djh2zjzdBxP6vPz/J9wxJvJs0Ag66aWWd8LlKufEfivKZPaz7T+qF1WBgd
hUD6fRJ0Un8SF8Kg0FHLiO5ItS5zwUowKUb2IqdqTz8Qa0dtT6s3fiFXiKb4dbmS
kRnsBOxW/bfjunGtxbLiLdjSiiGTU2bL23DuL7v8TGocqj/JbZ1znqCfkIazZSnG
FV0LH6HTXTZ1k88bmdlwvaY5z0HVEFNZObO/oW7rHaqfKUFGm0p4K90bBjrr4oFV
5PAcqNmFgCEdoMZCG4rXykWWMPCvz1F9R8T+UpBZdaL5qOYL2vDbZSljf8g6SZ7f
0nEOmoQVDweA82i8qo/uypgBU9NdCKV34N3+TzGt3l972NS7SHCpm/i0qhfxcGlH
HUGUh8LbvNaJ/AGqLSY0xKcEC/u0hjh2yjcwSvyMpbFn/lyOYRLF34XR2zLWWUBa
vDKSq2awBWMIJdYcgDVc7lnfHXDGsbUaKqCj3GijUmsFckOgffBh4SFoloCDKlTy
hq0NO9f6o9QQui5oL2rVWFientjCzmmsFR0QiJRFWBB9hekIoW/Cnyqj589Wov7j
fBUeK3bW1lapEYncQ7kGTO/+V3L97jVLL2nOjTLLuY2gB+v69EMYTCKQW6oBLLEj
TJqdhHDgglAKeWW33hRVOz/KUe9ZnxeFKzEsoZGxV3KoawWj7ZZNRy/699wCCqUs
OCt+EXZdV64CGhUQF801f3YVRsJAESxn2YwKzqrxrHODcmhgSHJA03qRoDiiycdH
S2FVRHq0MC5oPw9I6gFR06l+1ftgHT/cP2WViWNC6N1YVd5rMVb3EQxCCPtfi3Ek
JAHIOWtOltWYjgnOVN1bcbWjLB7M47BGm7bTvHLuGqA6XPn6qIXijumesW3nR1Fy
Nkk4g+AL1mWHyT1r29e7lV34Z6gMiC3+hLiMq5Wyyoi9dautuJ/IPSus1b+WsbwZ
qXkWuK8By5icLYruHM9DM6cDiBdhq/NsBf9+KDYMJpizGeabcazLTPO7EWOX07dx
CaJRLTl1mhOrMd3HhuATRJcI7SsKaqKYvcPXCvYNZa8tCym3al2ycEr4/2T/5hEx
Tg9T+f1TmZF6NRtYnVc3ohHSXr6f9LNmSFsESKrwyI61xrJRpvqxSns71JDdnIlK
yz/0FOaEKXa4RjWbWCOVlGeRk9sJE8zuyBk9ivP/GPiB79+dflEUFajSYOdhcl+6
MYK6AHp68XwbhqOMOhkOp9LtiKOlsepZzAyPrgPg5xaX2NAp5g81dmQENvgpZnpW
rw8WOFY1ivXd4D6XGL3ulmGBds2bEYTyWD5zm+9fHORQwrFC4ZKwPwOmvT3kPe+c
7P3np0/AxMtHxWbZCZddCqro7up7hdNLT4+G+53oIBleYiMozSLZ/gciVOmOqZwJ
Pm+2jgiXITpH8LSUi06HssKJ9yEfcfl0BQx1fafhEbbx4B3wE9fCuDb+swYsxl9Q
ksKFkMxaJTbLf6F728K2M3nXcWAheVOkmGOsAxwkK0NcX/dvQlC5zCj5lWhkP9/q
C1gkM0ilVrPmeJVV4/TVnzno9yY/O5xlHWwcvdcD/dENbjY8YXnj4ksfzopwDiM5
pTg6aA+LsLu5cKd+GbV4Os/n25kVdxzpbp+pvfJ72AzyTSqPMAp4sI3NYQkaNH/S
h1tKmVvTwHLCIMOcgH4D8Jd9cFsbpLLJkzFIY1syd5rGlE22Jeqgy12xdcUmTvre
UYft0S7tdsYeRcvXIGRrw8pDYijzH5VNRbKJUDnAReNbHXl792iuwikq9rXYOFcT
o8lI7O3UqhYa6QgaPEJJr99mgn5Ga6HkexIHld/tZqucePEkUWUNlz37xugSA9fr
//7olRqJTqCTJmIGEHC84Z4wQgj5QWw3BXhY5IaC4i2zeFlEUprJKLy90cSQJz17
vuDn9/+CYaLUV2JhiSaD2OplXbxY6/MHWouwirGX7b4BwRYsUXSw6bnKGshOn/3t
Zorj4HoFpny3s/9Ou/NM4uUt75+BwHYNbOyBQhwlVn73MpX5NimcaEJV2Fbe41x6
0yHsIMXWGWKM/qK/ilTVuzXDGtVde3tFEPeknNgL/0vNgyiY8fst1KseGOI6Rxn9
0S4gpe2v5nWRwEnBRgHnf9pJqkbp7pawMfyDU0AAczMYzwjYy5GjTFaPlZjAFoMd
M/wNcLWQRmMyUF/g2oHJeQqSc5GwKpecEtjIG/Wp9LuyiYCXagvc5KqAaqW1u2CT
dZKKmiv/PWbHVR4YaFYnDZphaD7YUA5c1ilzVro5Ak+VBO2P0Fg+SQbDabF3Xgbg
TW40PKvSLTe8KYH96N8TemZztWGaOK9SgoI0x/6a/vSSSpr0p4808j5212rCr/nW
8mVkIOp/NQv5flY1T75sIYmkNMBsCody6I3KOQyuBlyEaoh6VAlE3BWOHtFuiahY
eBf+o9yBnXjHwstKW/msCq57fk/hVWp0ffXISp+J808N0iTN6USL5T07Z0QgGWVs
4MdvnIRQFVDlrtGKcu4JCBZUrJ0LtFH23fVerBVNimqfF/v8Ofv+jav0SJyaJ5ko
w31UEXNqKvmoc9sTf4NTmFWHC/IJqZdlwiTYTCfXTW76VWNI1py9Bf6r57QhXC7g
/z0tC9MM97upq/U92lujLhdnqd91hJidGMzPy4ialb/usxHw3pdlDi3DOOEdrwGA
rrmeQwch9UF3NoI3I0MuxHrtv0cMFVfwV9BTRawvlw1MD/SnzckLWHdfLYf73h4Q
MqfilC+FpdqGkR+vlsTXH2j9YDLPSQrYKunAN4aMEHSBNA/CfM4pkElrVlpZ+a/F
4MaonxGJmy48Y0sEhSifyiTxNs4Mj0g7Pufb5rsPqhBo7ixPXGho1g5WyFwq1ZXI
32/iHFrGeIb1c4AS1nLnTKzHggbcEGpfJfBDyJqjCPn7pFu/NmPJBW6popKhGk+V
SjgkwOz1rpZbgryhR2VcrEazbIP0K0A0oVeOuEL4T7UzT6J5UvLgjJtMGteWIXbr
UtCThbqLKp+zYEg0E2lxBZ5LPqhzSQeRzgG7qgbYQ4OSyZj5Z+O2oGUbZWTiS/ny
RfgVw4ZhrayXskw5KUP43aLxpgg2fOBEerP5eQpOcfMPr6uY8PHTgxYv3/9cqefW
8IOKLasc0jeztV+zs8J5RehjQ/1PSr3rRQWMFRjwcEkQwkvzh7y2KNcM2Tvrh+Jr
rPw7n76vhG0NIdZa3lHwNKn/JH4DzG3YLmtN/kUsR/VID3Gw45bDUDFSf3egNre0
fgjio+iu5zMv6nADKh/t5nJ7e1iEj6F0+kNaNJ1eyRrLcE27iKRYez4yt3UpmDb+
FjNGj8y++ihf7ssYj2j1q0/NX01/yVEStnjZX6QUTaVWoOD2NyFw1M9R97LTEMm7
t1pH8Y+g4+smfYUdBxviWZhJmagHknMsuDGOBB9qfhpsSU2/77sabi3zXxDwwJVn
xdAKeOqv2QK1hyIILCIvy1Hmzu1zI38puBvoT7kRZQ+9H2d++PnVne6Fq37mK4bF
e0lUpEzY6uL9sBD08o0uP1F++/aImZ+5wGQxAWlpDqm+rxVmoQDxbhPAkt0z7yyL
822WJ1lOsoCwkgCO2d+d6i7hA2f0PlhUmzROPhwe+B9ny5RnabtXstwbygE6tK1w
QHExQsvnAO1spGBwgPRNF4/YihUlCBNmPOJYi1Leiy2qPmKUO+lZfvY9/4hq3Jd9
S1LmlhxRlt06c3FCVvpc5IGhk6SB3PqRqPGh7bgNU4dWbLv4ZJXUtzEwmsAQc5FG
5PfOLTYcl0bodStXQY5I68InN/EonVRV6wgEU7XaLn4=
`pragma protect end_protected
endmodule
/*************************************************************************
* 浣滆€咃細鍚存枃寮篭n* 鏃ユ湡锟斤拷?020/04/26
* 璇存槑锛氭湁闄愯嚜鍔ㄦ満
* 閭锛歺qandwn@sina.com
* 鐢熸垚锟斤拷?020/09/02 14:49:49
**************************************************************************/
module ehdl_sd_init
#(
    parameter DEVICE = "AL3" // "AL3"  "EF2"  "EF3"  "EG4"  "PH1"
)
(
    input   wire    clk,
    input   wire    rst,
    // get
    input   wire    get1,
    input   wire    get2,
    // set
    output  wire    set1,
    output  wire    set2,
    output  wire    set3,
    output  wire    set4,
    output  wire    set5,
    output  wire    set6,
    output  wire    set7,
    output  wire    set8,
    output  wire    set9,
    output  wire    set10,
    output  wire    set11,
    output  wire    set12,
    output  wire    set13,
    output  wire    set14,
    output  wire    set15,
    output  wire    set16,
    output  wire    set17,
    output  wire    set18,
    output  wire    set19,
    output  wire    set20,
    output  wire    set21
);
`pragma protect begin_protected
`pragma protect version = 1
`pragma protect encrypt_agent = "Anlogic"
`pragma protect encrypt_agent_info = "Anlogic Encryption Tool anlogic_2019"
`pragma protect key_keyowner = "Anlogic", key_keyname = "anlogic-rsa-006"
`pragma protect key_method = "rsa"
`pragma protect encoding = (enctype = "BASE64", line_length = 64, bytes = 128)
`pragma protect key_block
XCVUkVvfnlPoQrGs2sI3cmIbZtwqMtJI39CkGOeznQdCpO8CD1nPbVGkNefB+xly
alv9ySQx0LfQzpIbYqmfGLkLts4cpuf/GEMpV1Cy1GBSHI3yBdxjzK0TGg+srswV
cQFplWl1TsJhijAYIVTj8QW07SRWZny0ReD4EKxL+wA=
`pragma protect key_keyowner = "Cadence Design Systems.", key_keyname = "CDS_RSA_KEY_VER_1"
`pragma protect key_method = "rsa"
`pragma protect encoding = (enctype = "BASE64", line_length = 64, bytes = 256)
`pragma protect key_block
Ivwfo2UExM5ulY5FnlXr/kibMM4671z/vIxhUKKYcVmqolEMa7NEKjQsBFBXJ/eq
xjB45YV7c8k5QfFnlCU/44giQ0CB5MfbphidJBguTSGvCdTmCdnSMT4BB06eSgdr
mkeBO+RYlsqr6Fp1fM5uDb4qy2uy/JcWmP8l3Cr8zZV+rcMr91alQlhI13F0WOuh
TU90/VfgvbfLdUkK/gpTvv64MZB1zqMUNdsKZB6K4t05hNye9JuaUVNDErQZUJ2V
34WqyV5xDQl/4nBH7hjBRCrE1V8TZcrNn1AlEF3VVgNFYjBJ88zwy61JHljs8SiS
VHKxY8bwdXXwtv/zPSEyBg==
`pragma protect key_keyowner = "Mentor Graphics Corporation", key_keyname = "MGC-VERIF-SIM-RSA-1"
`pragma protect key_method = "rsa"
`pragma protect encoding = (enctype = "BASE64", line_length = 64, bytes = 128)
`pragma protect key_block
hZlnoYMdeIolTi/u0u6FyQsJm5E+bixpqkX1X8+rUUpABIl0m6HdcQ40U6+pOVp6
ZeEXXH0QagE/Hvc7JIDLJ6vaMKJgN9mMAH1XjTjx7Dvu2gW/rD9TmWuIinoXqnB6
63/Z5PFCnnENHfp11zSXI44HcEfn1f02c6io8i58iQ4=
`pragma protect key_keyowner = "Mentor Graphics Corporation", key_keyname = "MGC-VERIF-SIM-RSA-2"
`pragma protect key_method = "rsa"
`pragma protect encoding = (enctype = "BASE64", line_length = 64, bytes = 256)
`pragma protect key_block
L8vRxiowpMEr+IcvvLIRQu22rP2+7n3593Iygpj1lrT/0eWutVJ7F/2vlBvCcJEJ
ZJZrqXN9JsqAyAxjQ2eayHkwrBU1cbNj1/LlOB8triHam1DqAssyXnrHQjxRNsy7
wK3vd523NDSzr4wUo/ikNXw6gmkfV5XC3yuRz/wXmkfmcIqQ898GAm443QTprc9X
1T8Uz/v7Kz29fycxIJhPck7i99VL96tJPZ8kPCd6G/64ZUZpGbOqsiofyz+KCzV2
FQ1MaimNApKhgyGiIgK67XkKX0ZCZTL0fQcjVYry/O42tYbZofKydHlMy+uaBltd
q264LxUq+47o6PutgwnAcQ==
`pragma protect key_keyowner = "Synopsys", key_keyname = "SNPS-VCS-RSA-2"
`pragma protect key_method = "rsa"
`pragma protect encoding = (enctype = "BASE64", line_length = 64, bytes = 128)
`pragma protect key_block
czoaoOAeY67/0SXd65rUhIjqE3/Jo2zEawcJF6FGclevCQuCev/FGwJuqrO7G6G8
VQMCujHM2kp20gSzoaG/rlKjTiPd6e6k4P1fs+J6wzumnz1wiDK6eby5BEkSiYSz
sSrJzlrN4XZ3//c6p+MLjptUcNUIusYEM6hQoDTK2lY=
`pragma protect data_method = "AES128-CBC"
`pragma protect encoding = (enctype = "BASE64", line_length = 64, bytes = 4672)
`pragma protect data_block
cW1nVVF4Ump5bDFMM2ZjT6CJOJFuX5D03CCHsH/FjO2JMbsuvQVH8cXXFF+gkkpy
ZwKiTAgHPIQ/224h+wSNs9QisT07W5HYUWtIdUsRAHofCE3Qr3bwBMNTTRwsGdDv
tVUT6p1GhLz11SYKcPKSM4M5RY0jL5kdAe4tM/axHCn7a55teJ3VuPlctz1z73CA
usiBflM0biTgUju8vy/LAn0Jk4KJ8ZWx3Kh2yBHkWSCFHYXWz3xCU9zk6Wh2EAUE
vIvrBnUJbbEZNBeZFeXvkkGC+xmLZYjvSKiPHgL9gHl+onaFLbXIS8nD7sHV7RPr
/05n4gP1nPiUSWzE5EmK6tArN7rVrsK2tH2gq4KGwTe686K2RqHxJr8yOIMn8gZb
AJedRMyQsfgYd7FD/jlKX6Yc1e8+iUPDJTL1vZrrBtsEpPdx8jEkQSQ6S8itQVA5
GSsx6BrN9cFvxrZxrR72BddKdHERUVX97zNw3ZbfSgmRQ/KHa/4+sHHIr0cWICR9
ZGDE0UDDgCicUS9e6wQYPcDa/FqJo4jq5E9YWrLjSyKIk4cELamQL95K6VUeNmU4
Ds6Z+8l1Gk47GYtGvGdE4S4m/ZFrxaWD0T6aaWtmMik5vTHHam4cew12MIwJBQDK
D5gUiweB4YmdDL2fvRRtVOfC2AAoe+nrw0SgioaEzqA+NSMx40B1/HvOLxboxeEy
RepM0ZeAZ+AHv4cPh3ZcWY1Z6KNWvO/48crReIYtojkw2EB4YqiNueDkvn5b2w6A
vzTRf5AdwimbIfzymcCRMpOBRyZuRnNyAIRiKjb/V9xdsmbdSr6CW4XTxTU/OVnb
X3qlNm11eu8WsJoCKJ04MuGGe5AanqLHZkG42kmOqtTHv5Ka51UBU2cz7QgiHW8b
sVyywJKYgNrmuDlb/jcJnuYRuAlgygMcPNSmpc4mQT1LzT+H2TkIf4Bkk9DLGSKw
Epj+SYflUKlS+9Ho4XDURF7nC82oGXh2T8ciJo3Z5SN7thAn4oEvD7zGi0UovHs/
z/p5pkWbGq4HOFMdM1xgrsdWmJ5senyLdPaT7pheuEZZ4K7BYE8wTcYDrX5Vyyqh
dOerr7AXIX/jLQOAc8DqPuBL+rx21SgkWu4YantJmKQhyGjcMX0r2hphc3BH78Gh
Gj/eUHzQDX5lKgOTgYjR8BzDWszrOzYADDn79FnTzluo/nLilBvAgpGQ3w3TytUI
7v7FwWIBukz12Gu8CEjKm3K7YOGL/PNiv26GckknBO00Nbl9sYkNwY41QssKy1Lb
P09IbN65sYfjoCmMtvbV/N/ZUcbJJ2LKcIXWmzTKvv8EBXP2dix0tPe7G5WTe3Fe
pSg6gDcRI+LoVbW7wzdf9ZMrHD0+UqwbTVzjWTK7Owa80718ab8ionobAOXB7M5h
xtsMKQuibSHBr9fQM9VAF8OQBZgJhPyedyjmLRkZQCLi2dCq5N2dQwv1LcA/0wXR
MMlHJm81Y9vxhySAMqDKb5xH+1grUh6NRpmCkOYNGXgolhCdI0Ee5uWZZPkakvhX
iStnqLxFxJBYiIQ8oOpAe9JxjvsMeXyQwl8nQxowTg6EykS463M8LdoOiuyHiSB0
U4Bdtf/hw9rwKwMc0CK9RjNs0zSanPIsZzdv206kV6F/QIr8fN2aImTt0LalZlep
xCWWmIgtY21I7NoE+IH0lA+GSMY50GTpV1YnZLbyKTdZKq2iweGP/tH3QqYdJyqw
E8+pqrpGX4+b9Sud7Spb+pTiOD1ubkQEV8pWUi62qx+JzbSWxGfw38vy+9iPe800
PpzcGeITkyZP0okO3eLZVWk23Koy1tRhAj/WI3zjJW9+dpppKtD8hTB4oQXdVTkI
GdsPtXMDSVCmuArhgLunGUh4WRRWy5rX35y41j6E6o1Hzs5GGHXLtYrE6Dzgshoq
UumDk281StJK4v6KzEkO6LR2WIhOY+n/2p+7k/K3qJXKxtOiN0VQBSQat/VZWEdA
AzRA06XKEf5y8p3d4meEgVbw47jmTE2uQ3/KuMdKXPnJ5sWMe+pw8gI+kDHROdvF
6In7h1ezBApSH6rxh/4XBi/+VL3I2EEEsRsL0O6UXW7xDUpGF4Pq/9Dq50/ZVle5
dPuqdBPgvEXzjCJu9dGWk0yGMgMgsV+/6TQSaEI1pgBiHT8lYfiXK3Pas14gBjYg
ZrTgVJjs9m275EOH1bwnQbXRDYrjZkgWZ0hP53cmHs/Tci5WkCq1dejWsz6mSqdz
fqfegf08cTb/zRqZyRCjiDzncJx5OQod9MNYjOFLA/AsadgKTj23eu/BTEQF8EPy
W+tKG81Gtsq7CLtfhn1flrMNX0N+ptRI5Kno3zhbPrCaaIKdPf48IMHZYAP5q173
GtUCXpdQOP/7LaSeJAjDarT1LGwDz8JudGiAUZpEs6i6lScQFYutciDTM1ThTgWK
omwcEYWtaQhrGMq6+EtiHDU02iWj09s8/qQu1OkvQzsSGjrImxUDTLTFkM0o5sti
G4VkPJsLoV4OThxY3mZX9vzvbzVo7N4rbmJGP3W2Cdbypx19rIy3gsG8XDg8DGWi
Hbyzt2X7GbzwDzDiKwL2h72drL4KZ4xyQk3ohGx7N5tmA7wQr8xft5PsITjLqxjE
4sG198ib17evsBHCnSSzO7qZ3OabrDAQfS6bmXaPgajx5T/pT9R64fjYA8vrHNB9
UciQqwL6GG0rAhXu71gbf/OUoKc/CMvzH8M9OOeDvcznKim94a+gC7bhoYjFHob+
SRbNMUaOI2TitTRT73/3nqYSpd08IfixP0MUm9UaZqHJ8TKacRxDCKZrozGSORdF
UacyQNQk9ORGghhJDXxaXtuZyE05FtemSIyxzsMTscgC1bv6VkKyxDhKcTR23LIr
g0rFEJLD6yg/K14bmz0dnl3DOAyLkuAvrQhhLxnlr+Y2xeT3OZhb8j5qOMsVmvEb
yoHmbvzbH4vBnejR0MF1SOiDjr01aIiT82wO19+xNAPY+Sx8gavqe5GZCuKVGegc
pEPmJHvKI3tcRGPQL5p8za1Zo2e1iDVSS3jv7y6AXpYbsgEJNEW1my2iYy/tP1cX
OhoIYr91GoFCsmFH2t87PG6YmkBBQh32UsOPC9X44OrMJPSmHpKGbwwev6z1kFK7
mmKUWf2myz4PeDr8P/eZrNhhSH00vcFrwRtlIb+jf6WyP6CQg9ZFTytQlJgj5xxJ
ZV8/DISawrM0Y/VE1LWjJIGA3Gioz/HT4KeyITNmj4UykYqSBdwPSwUXM95km91g
ucixKn8wQEfjXSc8tEwDZ3slaXEqpzcAQrzV0bEIKZoyPGlgS7hn5629wOSpLhfm
iBd3oYHSbFY+I13wvBUVoXuA7SqwGgVl2ys2bDdluAPgN40zBuRzfOmFHprhudV8
ZJgjuSQ0r5+fN4hEvJtca4vu1L/cdnaD1qYT+v2drRa8N7tJIIaz7Y1njubaGAU0
sddW6L6O1MMFk5QHhpZndvD/ENV4PQvRc+iND40dDL+jG1Q7ht675XBvv5rSCuEx
Q3JwouO+LvzVUCSOlZ4Aa0AeMlclz0RMq+TRpyEBUxv3VB7XLmcu/9aMd9eRvDTg
Z9H0DmeEkGdSU46Gtz3j8F2F6x8Rzh+ViIFf+m3mP9hxv6FuTIZUBiSJrHBJR+J8
B8Y6Z2EMZdhaQf+ZMshMCajW65PtKza0oJ664XM311prlpqhbYQZWk7xe6T7eKNH
/eVRirmPKc8QMbTotiMszkmdu2sysBpxVdaq6hN8yjX6oeQQCKJYHIg+B1xAp3iZ
+a1AVmxkOG7ddx9BSnaY4hPxkHNb0nqs5BLsPpvjd+7cxvuB2kIJJJa9Qn2QtbD3
xXxJJqeURsHvEgr+Qg2ND89DelzJ3Ap5di1rF1ZZT1XQt0IcSr9D3xK6rXCyRl7O
noYtPUahqCPcHHfJbOt7ZM32ZszjPx7QgrdmTX9M5sk1bJ7IW5mnjNhGZBJO9crd
RiCU/dCC7v45hB4D3w0x389RFJA7KdYlcOIIpDE7kDeJjm8CL/7MTi3waCwPjXKt
9cfzyBvbnr9+m1COofc0/Un3yS1qvQtzbcosN/P76A0oJlmV19XOykfE1eVfW82C
pdip8foyvlJTq8MWjpaIFoZCJRjisaPBMcBcyAFiVJ5tuUXPJ78q3dn7yKZTvcNn
VMlMT8zC6wPaJiCdA1PvHWLM0b9yV/rdwyzKnXFoqSzAcrejtSaSJtZdwYeda4Ig
1A7jchDWAOCbM/XdRoJzC43Q5HtcEdRCgHEpZh0SYrvfSEop6kM6LuZcrEE2UeZ4
kLoN9w00PadX4ijtqCZ1/zN1bOk877v7tZtuINRNyB8AXngg4wMPYBBcGlN8MT37
YsVH4VnCdZ7lChoY4tPS5P2bk2JucBjoqC5b48bT7ChhTWUHIABQ5QwLxL3Nf2Yo
X8/QRRoY31e6CQ7TXLgFinz56FMJgkQ5bi7zPUDx+Kn2/hhV5A3kRS4VRO5posGk
nkuGCDJ5FG5CyOXkX0lBzm366subIy1agnSnakP4F6be0eiLFPPGuLvfR5ZHtQf+
5/p9hdZAvrur9XrKjsLFFf1onCdtoC/n5xYRxKwf8GNN0YMakIQCFFVMtybiDcJH
j6b/dCTmvLLs8npBY+j0Ip16Ln/fYfUBarH295BxOg4t0DzZwGuv/F/F+HsUz27P
6IETDq/Uzfc61WTr7468YaqxE/lRHEvDegF+uYSZ1cPmqlpk2RVMSt29Pi07ZtGe
6L5ufuWF6qVJv0OEnuBeL2Njg24xVX4PPf/l7E3ghU0+r+bWCHZj51UD2TKtz2lN
GmIRZ0d/QSPrHsr3/t9CkYNdko/FFQ7us64LIO04rr0L3ZXRvwDwgNs7cwG0VpRT
yBUZdpClD1U2x3YH+NOih+3DYD6Q2rhUFw+BzbiI9lDHLC0PZ4A8z54E4/fL5RY9
tq67JhOsuUmh2fe9hJexSadbvkRgzRh7ZiSMuJ20H7rXjw6ceHbhI+rw+Y8SwamY
/ewp6FdquYtmMLuc4bJytGfUbXyQvAv+3QH7qVU2Ys3NDEwC0jUefxYwt2qTt20f
31zAnK/JIANh2GyYW+25NK63tRYqSgMPY6tg93a5UyyIfLbLhBIWRtrnZTrojcZU
62qOEiMD+9k4ljMJsc66TNIR1qtXljosIbrbBL4kKK+9gdFvKhLJBDy7s0PNElzD
AzpPQBl8twjPM9co7msdX+9CFnGpWLNVXM1FidERn/7FDWE/XSayF0ZS7XSqQXD5
h8xG90b9ONFVEOfhXIzd8IUwH1M9+VMPn+zedzQ4M++W0LAzjTqRS0+BgF8cTMwl
Wd0xDxriJ/N1ViFjhF7mFoS9fTrjT6uHB2ahS1iBVqEfWn7cVrpZODrtQVL97hGu
NIdjTqc9AmGSRGuVv/P7C+XF2ibVlIYThWMQa+VNr3QDg7dD3vJdNznR7tguqP+z
jBlB7ZD8fMpdfbgctc8eRo+J3FR7a7pA4LCz0pisUutjTsn0y1VlhA1PgIF7ycmL
9OZlnmsIubsmPZTUvFZbJyFSAs429mmBk4fs7ZvZjVozKX1hsYmzYzl4XUmXltYg
Ph1pZ5dFXc4cTTfp9rKuiPto6i2LcfDarhlvVwF0gCZ4o8Kp4AL3dmwqOYqg8eB+
6Wd6awb/86tI0dpXOSIgvEwz7mdXx+hzkdatdk+mfvhatLaKkb3osSCXcuWu9KD8
SL+kN3uuEkP6DZMU1RSIT4gheO0KsHzAPUBoOASW3UKaShEsKsJsChs+cLfSQP9G
+4sc00+XmJVUJJbnKqjskz/R+kKJphQ069KisDq/lVxpKRq2oUR3eq1fbHQG6OKL
BmM4BXlpAdN14VEL2xWEHtzuzZuoUcW/eupGYgKpM4s6GND7MT6XiWPS5K8yYjGd
lQxgGDGeLLQqU+luCx212QHZAlN+nOJ+usKwScdNtm89/6ojDljyCqEoXyXEA6rh
t0+mj4CtGgvwLVk/Ag5hGAUbOx8Rb2TVTD28Dp8KK4rWMlZDh/K1/F2Oxv1tSMFr
DqdBB6C1RLEw5Td3goZumx8ItMrwLrv+VLYnGuoaTOMix9NaRAyTI8Pa0AEqaJMT
HLwTwXK2RvggwfDoJqc0wGXLiWqPwWvmpfebYJErlbLTBRNWoK8+vnWo+pkbBFO2
K8E4LKNuehiwffjjfErZP6mHjaccRF/eqcgJtde1U4Ho/goQhd7HLBnFUmW/TJ8Q
rOrt1qhXX8I4jNpcMS1PQQ==
`pragma protect end_protected
endmodule
module sd_read
(
    input   wire        clk,
    input   wire        rst,
    // sd io
    output  reg         sd_sck,
    output  reg         sd_cmd,
    output  reg         sd_dir,
    input   wire [3:0]  sd_dat,
    input   wire        sd_ack,
    // data read
    input   wire        ren,
    input   wire [47:0] rcmd,
    output  reg         bken,
    output  reg  [7:0]  rdata,
    // busy
    output  reg         busy
);
`pragma protect begin_protected
`pragma protect version = 1
`pragma protect encrypt_agent = "Anlogic"
`pragma protect encrypt_agent_info = "Anlogic Encryption Tool anlogic_2019"
`pragma protect key_keyowner = "Anlogic", key_keyname = "anlogic-rsa-006"
`pragma protect key_method = "rsa"
`pragma protect encoding = (enctype = "BASE64", line_length = 64, bytes = 128)
`pragma protect key_block
QJYqEgnnr17WMKVjdOaIX6pauk142EUzfQ4Nxeh9Xk3BKpreubae+xMJ+qg1DFd/
dfDKecc7wzc6kHDZEmh44hdHxZWaYr+6+1Xvw5q9+cEPPLJvKlj79u0Nbx/c4emN
YCTpg49U4ehj4Qet0nUrBvuZ/eAJ1vy3n1oyGyzrSFw=
`pragma protect key_keyowner = "Cadence Design Systems.", key_keyname = "CDS_RSA_KEY_VER_1"
`pragma protect key_method = "rsa"
`pragma protect encoding = (enctype = "BASE64", line_length = 64, bytes = 256)
`pragma protect key_block
GcZD7r3Jwl2Gwx73kdLcqsGkbos6haShaxCvpEiwny9mSVc1TIseHBwLo95iOR23
pKPuzX3J0a0y0/2LyhYdMxrRo3C9I0yTgNwHZThZZeZS9xjUkF853EKUFMEQtDef
nIb5a6R5DVPxM3DFVmgucj/0bLkG3yoYqtPDRBcTphy7AfH/UkAc/pkNMkmeQRlc
PRuWSgPvuivTxGhUY2q3elzCYTcoN+MyueiB0EV7UurmFG73ZI4woJ6jUVzcLdDB
KBi5rdptxl2xs8mzwDhQ+Ei58RRI9P1NtwGjSXXruA+ew79QUvZMg/vCFmu45x6H
N5Kn265cvd5hpbguVAEDHw==
`pragma protect key_keyowner = "Mentor Graphics Corporation", key_keyname = "MGC-VERIF-SIM-RSA-1"
`pragma protect key_method = "rsa"
`pragma protect encoding = (enctype = "BASE64", line_length = 64, bytes = 128)
`pragma protect key_block
kAYBn2udjmA6nQgDNYUV90KqQtHFN3Abt1etyUp1G63ikpedkT59sxbLxwn+7ysy
omD1ng76xssYsKfRgkOuwp0LtrnCQcYXhi9giRKTb0oEDZjJUxSqn/4iP3KOWoaj
iXbJYr8Qeag65HLa8WFRBy5L8sQr9ksXGKul3mtSwvE=
`pragma protect key_keyowner = "Mentor Graphics Corporation", key_keyname = "MGC-VERIF-SIM-RSA-2"
`pragma protect key_method = "rsa"
`pragma protect encoding = (enctype = "BASE64", line_length = 64, bytes = 256)
`pragma protect key_block
aGm7hqpiPS8QBvdAjePaIZCIPKQPtKGAJigOzJ+Rc7G8SB4nZEUEnjHxeoVd92M+
byzpQ4ura2RHUQ4SS+5zQ176LK0mfx7UYu6W1hYlFSC2idxYcyrNoi/g5Ftl5rXD
Nwaahl3JJgRMoXn5xj1IvH3JgHi4eLsWH2osCXUNPy87sNhDjLGJARiNBI2ejuhB
n7rNmzrJ9FhoTFee2sohYcvbwi26h4WPIHmjzWnnUZfFY3ZyI5qD01LUz9pMAo0t
bFsJe9KfrJna/vXUaiGGqNbHCr++kDXQlMDMSqmLGbLLvkKZMkoeks5OkkiIiDf4
hNuL6oeVyqPKj7+TbOS2HQ==
`pragma protect key_keyowner = "Synopsys", key_keyname = "SNPS-VCS-RSA-2"
`pragma protect key_method = "rsa"
`pragma protect encoding = (enctype = "BASE64", line_length = 64, bytes = 128)
`pragma protect key_block
AB5zlJ7fTT8662d67m5j9NYCGM6wTLJSgNQir+hz6CNCwtXqx/5WqZtvUhOWqaRQ
rzjjHGiP4fGNLEvsKJA0OOVOL/M+cmigj0/Y0Ggy2dxXZX112EMfMcj8Dgn277Ly
A8XiXs2fk+f2iGnacxpGF+gOaSBnRqAH1cxytXHkYHw=
`pragma protect data_method = "AES128-CBC"
`pragma protect encoding = (enctype = "BASE64", line_length = 64, bytes = 1600)
`pragma protect data_block
cmsxTXlvdGpjdFdXRldNUzKbAw/2whxAQ1/aCE7M4Px2E1vzcx2Uh34vZR5rLnIp
AFK4iCDHabrDtsBIf7Idl3JTD5EcZxXVWcCiZ61+nmnt1kY9pkF5njP1OV2yD1g8
fubsqgUiWl2zzq7wA19svCycA6fxwTL6uGDZkrnqyp7eEwfO2yPex5USnNndYK+1
82SHm+Icm4CjEzASvYQ+9FALIjgyhVJ29d6bCLrqWxo24MtmHr7yE4yD3UnUB61a
4DJNW6uPvVYRCJD2XLZP3VlIZXkyph6eisrKYJ8BLGMiDHTfjhXqzoG+AQ47r2zy
mn9swvfrwoHlGRZyNhw7jDIJOiKg90j5u5frox0e+C6/EO977oDkIFBFMWn46hPH
oHu3xt0i3N0tx6bKcs70DcO6i/YZTylLy/Qo+IvYspz0J93/9LVKFhxfKT2kdwpz
Q13SdGCs71ZA7/epXl0mkJqbAuJ5LlHeETGkTMbtHliCnPe6XBC2uenkyRY/8ycf
wP40syagC1p4wkwJ+PCiX5PwUqD7ojwiIYHJyUK+EgGqEH4aclSSja2zJe3YIotX
iS5WexlOBUgAzyXAbH77TbZU7spCMTOBDU1Q/5SgO+kOCIjGrCsxK0rwEPSsWvMf
uoLNXepPjkyPAg5qGK9sOM/6b9kTGPqReCtfkV9zYsrY12DPANGfRFWxtPQZK5jD
ctSBsZPmAuj7GV4u8tiMcwlLUjKGiggTMIIHQ6Erj3+piDxKk/eHuoOrInm40JHy
I3X6jXYmcMRBuU3wOtvo5+HbA/oPS7busvYy9e6KwRwZUamOZadRP/OTDDtBzvZW
+FJb/zFBsQdElscCc7wYSgRQ4szAF1Xnyiv+e+f3MOnq7QUx7JV0BB3wONCXqbwj
gFrC2EPghvjQy54SpKQsECUguVeEVfpYkumaqsX7WM07cHuT88GPuUpZgqNG+bvE
0Ngj2yDgBpSlunRPhr1gVl8acDvHBsjWQU3JMl9TBM4HBqQzkHT4YwByUGL0VL3y
d5lZ4XkpTg7Fp1QJYYys7XbpChZ+KwvG8DZq/t+xLvjP+5FYlRls3BxLCp2djRu4
yNTuqaP4VH38HpO13j2NivtQN58g1IpqN3o9sQQoOPrvOE/I/9TfGYCrNCwVyVcd
dnK9owG2xvHrheHc+7fqZMt1XFA11Hxb+xJ+cT5Aqm97HariFIHoRzTT8SJ/QIz7
JY0//ZWrJqb0SLn7TwbJKA+YqOUj3Rp3GWgM8+U4F9OIZ0mMvI7m1psAdK42yu91
m809mqpLk+zQCyNHd5cAyQCASWjo1mZEzLOdTxOOeS3BdB8saa6dyRzIUlD/4VHc
gltVWDGe2WLXcLxRdzUaFhK0aeg+3Pgd213k4O+xpmCn34HOJDAQxoXBQbIYcFN5
bjUfJPBUB6f7kjN1dXjB8rNUjVM+M3SIi7+i8NFYwgiwPuqvQ+fvwyCNsurPSzwa
wvM6le7/XoK7nL4s4XwVs6Hyr2VLaxV2mJa4yEd8ixb90jA58NPMKecV18wlnYWs
2u8PRTFvyOso47sMrJlVakx51pf7rTLAtzs87FvNwPVYMiSwYWMlcCZOJWPqhiXD
v/X3/w/yxjZEf6aj5QNNxa5skQFagLumyriXh6l0uyuGtigSafB3lOg6kw2Bsb9p
WTPBxeMz3aCaCOExyZAxOaeSpu34URYyEYo9H+C7n+w4EX9LOPv+kQ68anvVUqWN
x9avaBcSG6QWNkVVyPzvNtxeMxC3c++vFQu6FuAT7b5mX8TxX3F1AKZtb7MWbZ3d
gGTQlYSrBGDBDsrOG8PUB8Lv6OesBWmGybhWHgFVW5OlSq9t/3fQL2yKF/BudEec
LPNAPPMm2UJ/ZfS1VPmnNqY0G6vPzCTOklAGWthza7S9LS19ntuIpdGlclrPHv+z
9O4E9Vdk5xAnoAqejH0tFigyQTOPTJ20uQzdjhlxEQjHQYph9cvlspth0ogUmyDG
25/fjld0QRapJ4nERQRZ2Jx0A52bnWnkkIEikGBQd9JxzJH46Bvut9fM13MZcz3d
+M6of/KztYfgR9TNzZgBupHQW45TBSdlR8/34JYgGQXblZOxMlc2jTvWvqOSIsfB
tjl+9H8eGBgzTJsKjIExjQ==
`pragma protect end_protected
endmodule
module sd_write
(
    input   wire        clk,
    input   wire        rst,
    // sd io
    output  reg         sd_sck,
    output  reg         sd_cmd,
    output  reg [3:0]   sd_dat,
    output  wire        sd_dir,
    input   wire [3:0]  sd_din,
    input   wire        sd_ack,
    // data write
    input   wire        wen,
    input   wire [47:0] wcmd,
    output  reg         rden,
    input   wire [7:0]  wdata,
    // busy
    output  reg         busy
);
`pragma protect begin_protected
`pragma protect version = 1
`pragma protect encrypt_agent = "Anlogic"
`pragma protect encrypt_agent_info = "Anlogic Encryption Tool anlogic_2019"
`pragma protect key_keyowner = "Anlogic", key_keyname = "anlogic-rsa-006"
`pragma protect key_method = "rsa"
`pragma protect encoding = (enctype = "BASE64", line_length = 64, bytes = 128)
`pragma protect key_block
EoS1mU+YDly5DsoTEdKbuE/psfnJHlCYSbd/pnWYbKz6ENmzQO1AYmSl0flF5te9
ndoA7A/NqiHHiYEttvMioBkqFqbOoRy1CmiiyPrwCesNIQoaHp/7u6N2kjwtpDUn
TO7qJqNkGhiCWGC8VI8a6hOkkPA+WM1KhsLsweqOpx4=
`pragma protect key_keyowner = "Cadence Design Systems.", key_keyname = "CDS_RSA_KEY_VER_1"
`pragma protect key_method = "rsa"
`pragma protect encoding = (enctype = "BASE64", line_length = 64, bytes = 256)
`pragma protect key_block
nFmR8eFFJohBuvFys/1qJCDYtQEdlQUIDcQg2NkJuiU7uWt/ZGWvexAfPjMJbBUQ
5y6Wng0GXjt8Qa/vqGJSBauWOJuv/taf0ntiqD/pSbByZ5osZwZ6QRnSAB5TmvBE
sdDPdual5Kw1JMpqj54T4kKC8PxRC5IHobxSLxeY5HYXOvkV5Q7k4FC2BUbfP3+v
4aR2mUBCi7ucnZwFMp+k0z26AODI67UA9PC0q8sn6yj7MgbF1fLTMVIvHvCU7vNi
By4qsQDcyrafaBjnYPFPdH/1+amWCopRUEg3gNUVpI+/ffb1ODTS9ql/Mr4QDY0E
2oUjv7G69hOPXSXatQ3Gmw==
`pragma protect key_keyowner = "Mentor Graphics Corporation", key_keyname = "MGC-VERIF-SIM-RSA-1"
`pragma protect key_method = "rsa"
`pragma protect encoding = (enctype = "BASE64", line_length = 64, bytes = 128)
`pragma protect key_block
Gvuh/FiH4A1B3E83qGuNJz2hCWKljHTRspcMvhTeLM2S65Y1GYyrb4bAICumMsBW
Su2tFslUNUDCUdcaHIriTRvFwj931nfzHmtorjR7mHbEGHLZiKmyA1jdmKqsAfY2
Q7oB8l3zUV8XzhWId4ajRjZnXqivybYYuJH7cKbKRlU=
`pragma protect key_keyowner = "Mentor Graphics Corporation", key_keyname = "MGC-VERIF-SIM-RSA-2"
`pragma protect key_method = "rsa"
`pragma protect encoding = (enctype = "BASE64", line_length = 64, bytes = 256)
`pragma protect key_block
cK6OewOtvFpKLxWb3RnLx+EDXA0n4lFQSuxhBCuZB9/m0QfO0YYOnGwJOshEKI5l
+E4zAHQbksESRrrh13HzDUrPjdATZmMltZ461x+l0nVDG3COHIqhcYIVYTZAqa5H
t3rFT8w3u0mi4blhxjnxXNH7s3ghhGxmTE59TH6yFSP8U9VyjMLFNdEu6TMqqttr
VwpF2kCWjS9nPVdlo9iL4+U1TlHmgaPbdh7AGa9/0nHR0Jg7A0ASDMgOIa66TYNU
2lIgijzLfMma9T+WvkiFihu2X9bI7Lq1dr5BzFyycfKfZYks0fsv4aybxTlURhZi
+2jflLlumfxaE3IhCi53VQ==
`pragma protect key_keyowner = "Synopsys", key_keyname = "SNPS-VCS-RSA-2"
`pragma protect key_method = "rsa"
`pragma protect encoding = (enctype = "BASE64", line_length = 64, bytes = 128)
`pragma protect key_block
hRlOV2qjnPxZck083702ZnTa0fhMZkbLPtFzSNXoMTLLOiN9DhfYVie4tZLZxRQD
XGqpL0T+1fS/2zbZz9CGz6F8Br9FMoGR0cBtgUtX0QLD+scK7Yoy/G08hOmFPdSo
IwjJjuBwUjz0RulZ6B5dyjqqkPETi8YEzTgJn/+1RUc=
`pragma protect data_method = "AES128-CBC"
`pragma protect encoding = (enctype = "BASE64", line_length = 64, bytes = 3984)
`pragma protect data_block
dXRVa1dDeWhJSXhob1VSTY+W5K1IaGv+nNVfoUIFUldZOeGNVtkIdf+G9hZW4tIH
uRSsE8muNgiDZVhEB0IHrxurK3UsYX6Y+Xk0vpZAWf4yQtbY7ojWnCKHEYWyGUhW
St/64S4J5OYKwIAVvbLfZCvFMSSxcCKfRWo9SzMao01CaE1xUCunzLilIqfIngZV
EQi371WyErUVEn8Rjg2O9ccWMTzy5zlrf6vDCG3Jwz0hgrzWea3WwOpSf5dKGVJ8
wW3kJPG4nKzLjhgNyu1ZGHLL+BPo7ClQH3jHrpoYuSDXQCasqaZTqGPS4ol3O0sR
q2hf70BjxC7FkFNe6p5rxJ1Dss/NZfNt61ynt07hiTn2A8aSNMJJNv4sKCmX7j8J
boULFIoauPPBi3mMfZFPqJerNoXFu+HVbYRtmlJVOhdnW4tEjBUG+iBHSamftS6b
vh4K/JJrE1BVyKLUnafkIlvGhCFnR7AeI+hOJDWNIirnUZfYe5kvlolHwc/3gLtn
gWMpXF6jU7PqormoZqVLwpxQOKHvGGxQSqNYoLvyUPWzQPG/14TK2Uc1NJu0ReEL
9XHAx7OKxreobZzmHmsnxHVghWElxXaGmUDxE+5uK/JDpjxSYg5NC7K1vXPvOCli
XC6PZAA/zEy/9Brq4R2W5ni0DplfvaMlTU0id5c4Zlu387zRivKK7lJP25u7DY0b
cHzg5HkGqJ0GNbUdm/0fSyqtzyMyZ/VFBVnEOJaA5KUuc1r0cqYrNz4LA+Ptmkn5
oezRAytg4964t/3NYHyA3MU9+djR4lmgWqJZfNzFnO0FUSMp2PqWiCPoF4rgydyV
o0QMYWhZXUU2PKie25rwG5BqrP7Ewv5Uis1eJshE5TJtvn1bazz7hzCy9Bkbf56L
gENdtQy4R8q7rXwn8IFTSTPB8GJik2mu+dv0ts+kqkqOB/M2NwiLC0GI5x2psVX7
34kzRsCc5AeXMmkuIY17rEslMOM8L/4nMhLqx+kVHJOF6Csxb5VmHGUInWfcNU82
rD6fGUIVrBAbZnBH8aK5QsqGY7iLJF3/mk3Qr1P6G00NQjgCe2Vr36n2tPdEOf66
2d5Cn6Kt2jFHmsPKDZx3BeMWzPAewUckCjCQ/hmJCqcMZQMLQQ7K8ORC/Wt3QtkP
uSB1ePB/8RnVdU5qywFCTBplcvt2tr2jBeYw+2NqHEzTjRWLL5eBMmh2SJsMlAzp
HNxYwrAaq8fdIGfzX/4bU0OQDg/bL6xdWvw1fBpMyMQSH5MbK9ZeyJJlzU24TQi2
5U1m8UTE/uSpgCJO5OoZt1EYir1Wz/xnxY1ifjnvNp0rkLSkleaBwJUQX2+zLtus
V7Jb4JMpULgwEXwAQ1dhLmS3K4LC2Lg7rk6aXjOMfbfWS6DnuK+8LGsS8t/dRuJq
7rZkd8YXoHjM5qek9bvM5QPoL0CbVIQj3WC0LrOSZuuEGvNoCyrihwo81NDfw5eT
qRCabSkrGJitmNsI4Cc+kUFwqldLBr3hnEVQvXQMze+Jn3eD1b2ZIU3qqoKqPFQC
uEJN/cXbiq8YMW5FRdxUQvknYAlQgAl38tr0tI4CLcYqzBHhQj5o7u27odKItIWl
wHczb7To9XLrZGHXfoWMZqcaoeAKH8Ohf4DyYibeKg/R/jeYaESruRJwj8aXAFAv
SiIMBuBy8Hos7r4+ZU+Jvgs2wuNzno8bx2cMRQzRbdOOM6V9IxmQ/pQK9CygIQCd
eaN6lFVfR/TjIIvd/jdgAkA7sn3TXqYk4mF5pavfiqGXaNRWaklQl4XHmd39Q4Rm
oMXJM55XGMzDe6oINZbK6BAo0fSSw1OW7vD9UAV4tdfZOI1uT/3qq+0qQVVqgTX3
of6xymGnguJoqzf3npWSGecfj8Z5j9VpYGMNA2XLh72QEqdc5Et3eUbvWjIE7eij
kxs/Ys5xKj7LSOPDTuR5CQZzLQUsdNbxo23Iza6ybuEmmqphRJhgLQslMLsvxxWh
JDsm7nKt9t6UqrCqpek/4dP+t4qjBpBoQtWOJkGA1+Cr4YfzNKfHqsRE05Gm+EjQ
VkhwrzJo15HyvfNaIz8opNrKIHsRE6oerr0YedTOUVKh+1ItW9EmO3yEWEx5FViI
fQVqYRoL9Oiiu1RdvciEDUsc/CPaYX9T2KRZRCSD8DXdQeDFrWHNurQviaTuixq/
iUU8kb2/VcVYTtmeQRdcb6NcXPyWMtnpjk/sH2NKTBQmRSQAq3Dxg+ZZJ2H/uBV5
UdzYAl6GeIPKc4ldZdFXBISwtYVxlXaw7XoP6sjyqzS6DIkRJQFKca5/CHQOQiX7
6d1H3kwCekdZTY/r9RF02x1rDA9iZ09Bd5+VeITH6tivEpFcmAjb5zhLIBdYsn4t
3V9/aq+K7fisUjiD2MbrRjg6lp5wspEy57LomraY3Molohz9tzY0sy9wUc0pcGx2
7iyWLwE6QgFTz57f43ZEi6N8NEDbztGf97O61w2qdKsOB7lQqxjgLP+c+mIVeq3H
NLaJzlk+u2PqH3zrNnw/8pXlBVXUlYHiyb1bkPRVMJON115SRr1hnULSUz+joeep
V739feWOuCYhjKOXihbTHmNNMObH1bf/Gi5OtLkT5Wy/HoPry2dEpagUMHegHfHG
Nv6QApC42agUMaSWrJUpb6k5FSidRf3QYhSrLlH2Oog+81qHU3xjwo2t1xwE3V6W
4+Av9WcEOMi5DshatO9g6nQ4pJ60Lo3Gb0+EPffIz3UZ6GwzdhziIKJBAfJw1c4q
w8VTJinx8JvU0mW2mfPFpwN/fLoSmwqGg6w80qZuxSRw6pQR7aqAubWRFTb2AWJZ
VjiO4AtDqv1ARUmO8vg0FSpNdD6h8aAGzqDt7ACQAoGqam/4AwUO9Qs/b5VD7rN5
3+zCNhiuOsM3LuYUZ4BHgj93RUreuQv8UVl3262PWzFJUX1aURTtYsMC5oUt+3In
1cyEGlH963BFsiboHUeM14sjOF54Bt+MlJEIKechHOfBBmMFcgyLvpafYc8WXtZ1
vY49jvgWUQgbZZLx149KBgl98NEy0Zt5cWstKiKK6N+0BT+gOj28CjdolTyosyGM
nHzs5VgvZ9/sGrQbVheOuqzyXOQxWRiDbl0VBP33X/zKqLe13aJFtSJZZt0+pCez
r3cQ+QOT1uIOsKxkTMgRBsoY2JBHG9nh4fBTJMJAj8Nrg+Ouk67zCr3v9mD2QnCK
XtGlQ4wjt8kFLBuYwkHefP28CCI9S/RGLrvteqRcsYM2idVg0AALPW3ORAquXaoe
5tTEL8h922UbYY0PJE5ZSYaNP28d0KxhyDSnO8DxZTkpPm17H8MXKKsbveAjbHle
8SgOGE4gqQqwMyzdh4xeb7iG5FAkml7I3zohtqutWAbITTFN9rvn13W24E3TqZpA
5Opa4WIWrsltarDpqeM+9JnchFGD1Fd54i7pFNQjPyyYZtCN5NzbueODF3r1wM2S
Jpol+7HbGO6pCH9W/H/m0PBcjfFYrpKj2T3kxOAsrx+b/EcQk2GRAqXFtlfkvDQD
UGtcArvqfjno2ONTR46dJGhjV2JocskQskVEWYUmx9DxGI3M/CXysA18YStksRv7
zercY7BlVKwMvciYCJhXikMuuDQQdxzo6izt5PLWjVGWNUFAj/tujK1v8h0Cqwpr
tvYIzMGwj3c1maYRA71SOqkZ4urJgcwywgicC/rfH4eniaVcNuZPIymXX48r3BUt
eBOPJpIPZifduSVW6zZsUeb60HDG4WmA+3vnrisfifxmxYi6nFjpZJVg5pa9uLLO
kdAIavwwxyToir6NtBY1SiY1ww0BY6Fj/AMt1dBWyUlQw23GaCRXX4DmIXruWYwx
qQcPAq2+FnXGEPMXI/MLul61ZArHaXSdV5GPLgjYpVFJFB+zt+XaIULork20XKo4
mIS5IFafwiJmlPUIONblOF2nyI0MmeiYelzk4kTolWRLXmkf5hiS9sa8OvCFst8q
RUuQNDfT24TR/nOFmpj5JBwCCM+zBDVU57uo+aenhCG2015Gdc+kxTzOkuNdvK5c
yLOrXI7QpSA3qBxE92xIMawBNXJPbzWIFjfuvPeJwXJ/9bPsWNKr85ryoMF2pvTd
vp+yC1FJdBebVCJ3efqql4w+F17v1VomGRVm+W4mwYGDtQOs9uBIoI3ZcI+Fhuom
vVS6fD1RQdmZTUo9stLxhKJ9sOZzT4sLZvXHmWurVbLwXeEexYlxtOeHOtCJl1Ay
JSHiQLo0v8DMSGuyVU/6vOQwujAMWpRFx2PvUHmp4zeo56YR298rRCrN4SF4AfUM
E62UJ5EtywOUWoPx1JwlvmMPmnPw5Pstg+XW6y+K9OryPbQwVwqLAGcN5gI/DME0
lUS3Z13k7jtE2NhzsFJ0tmTpRtnnHr0aWHa/0+bsvh9SBJuZvTvD3lLd6iz72xSP
jNSNE9DlK+QoHW5/bWAdtY0YCOJoNve+gdWOgR6tuodifyo4fHLmGSqwLVhSuBBB
SxpUEmUMQgDvc4tUz49B37Pkz96G9psd/OkxkUnRaX3CrhMi5QAW0CzOf0ZsCr7t
RWeHTyshp3YMj1+bQND3uf6c42i3BmvYjB1i7EElkQJj/5XI7ZgtCE6Bnkea+Uc5
M8+rnoLHt5Qm2pFGYEc15ipd1pf0u1eXo3XMIqNGv2zgRah2QoHizqqBI7Ux/9hd
Z2ARAwbnldbiygUu6+uzk7Nl6ymH/spoZNC5CD0rf0wF6+40+IwmjIayLJOw/+W3
mXt7YuGMtW1gXdxHzfk9hbTCaG5vYt2a/OZ0nvfqu8cHPDDIvlup359E9RGQzJt/
3VoShB2tAC1IJolYg3L4p+SQpiBfolCDA9/Q1i34j+NI+72fP0alJYM2J0SgfrQh
sVzegj3eaSxkT7f71eOahYZWXl5A/hvH7E/nkHtKQ0GqCCR5tDwbtjDiUMVvG4zm
HIMDj0tAZQ1BVyu2Qnu2wRNhoZdjSA1ksMfX/P1LhUyJ2fFxbhkbTFRBM8Glox1e
TXhUDaFfDglYucTjo/QmS+51A4LyFLVmFf53cLvCU5qPLC6cl76dA+ytIhhMEVsT
abnAeAABfXlDwKFMFcrq4KSpWvp0orxPbD95DtzH3X4Y6VQTzx5z532K4C7E8UJC
tUJg4F+SJf4bsPNkKcdt6xaAWvU7ZpI8xN/4GUwQpoDyjm3D2Z7cPN+NDczOyZ9q
PhAuCNjhz1mY0zARpPY62e1nkJkhPKu4FQb02Mv8zNxhYaUQM5I9SYiHbVK6dvgK
YxyRkg8xBq6a46mMP0RbV8qKz42s+0mnrYyhvfY3mgw44NDMCTKb8mOA4fC7Dy5X
`pragma protect end_protected
endmodule
