/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	H:/AllProject/Tang/work-ritter_soc0.4/project/al_ip/usart_gate.v
 ** Date	:	2022 02 16
 ** TD version	:	5.0.38657
\************************************************************/

// Verilog netlist created by TD v5.0.38657
// Wed Feb 16 18:01:32 2022

`timescale 1ns / 1ps
module USART
  (
  clk,
  rst_n,
  rxd,
  tx_data,
  tx_en,
  rx_data,
  rx_err,
  rx_vld,
  tx_rdy,
  txd
  );

  input clk;
  input rst_n;
  input rxd;
  input [7:0] tx_data;
  input tx_en;
  output [7:0] rx_data;
  output rx_err;
  output rx_vld;
  output tx_rdy;
  output txd;

  parameter CLK_DIV_NUM = 45;
  parameter DATA_BIT = 8;
  parameter PARITY_BIT = "None";
  parameter STOP_BIT = "1";
  wire [2:0] al_000002673A54CDE0;
  wire [5:0] al_000002673A54D8D0;
  wire [2:0] al_000002673A54FF50;
  wire [5:0] al_000002673A54F770;
  wire [5:0] al_000002673A54F2A0;
  wire [3:0] al_000002673A55B0F0;
  wire [7:0] al_000002673A55CB30;
  wire [2:0] al_000002673A55C970;
  wire  al_000002673A550340;
  wire  al_000002673AA5BBF0;
  wire [3:0] al_000002673A76D950;
  wire [3:0] al_000002673A772F10;
  wire [7:0] al_000002673A897880;
  wire [7:0] al_000002673A899100;
  wire [2:0] al_000002673A8988B0;
  wire [3:0] al_000002673A897F10;
  wire [2:0] al_000002673A8A4BD0;
  wire  al_000002673AA5D780;
  wire  al_000002673AA5F070;
  wire  al_000002673AA60730;
  wire  al_000002673AA63600;
  wire [3:0] al_000002673A8A3F90;
  wire [2:0] al_000002673A8A5F10;
  wire [7:0] al_000002673A8A7020;
  wire [3:0] al_000002673A8A68B0;
  wire [3:0] al_000002673A8A8670;
  wire [7:0] al_000002673A8A86E0;
  wire [2:0] al_000002673A8A87C0;
  wire [3:0] al_000002673A8A8980;
  wire [7:0] al_000002673A8AA190;
  wire [7:0] al_000002673A8AAAC0;
  wire al_000002673AA9DE20;
  wire al_000002673AA9F2C0;
  wire al_000002673AA9DED0;
  wire al_000002673AA9E870;
  wire al_000002673AA9D950;
  wire al_000002673AA9F370;
  wire al_000002673AA9F8F0;
  wire al_000002673AA9FA50;
  wire al_000002673AA9F4D0;
  wire al_000002673AA9F630;
  wire al_000002673AAA0340;
  wire al_000002673AA9E240;
  wire al_000002673AA9F9A0;
  wire al_000002673AA9F000;
  wire al_000002673AA9FB00;
  wire al_000002673AA9E7C0;
  wire al_000002673AA9DF80;
  wire al_000002673AA9E920;
  wire al_000002673AA9F6E0;
  wire al_000002673AA9FC60;
  wire al_000002673AA9E030;
  wire al_000002673AA9E0E0;
  wire al_000002673AA9F790;
  wire al_000002673AA9FD10;
  wire al_000002673AA9FDC0;
  wire al_000002673AA9E190;
  wire al_000002673AA9EA80;
  wire al_000002673AA9E9D0;
  wire al_000002673AA9EB30;
  wire al_000002673AA9EBE0;
  wire al_000002673AA9EC90;
  wire al_000002673AA9EEA0;
  wire al_000002673AA9EF50;
  wire al_000002673AAA1AA0;
  wire al_000002673AAA1100;
  wire al_000002673AAA22E0;
  wire al_000002673AAA1940;
  wire al_000002673AAA1F70;
  wire al_000002673AAA0A20;
  wire al_000002673AAA0760;
  wire al_000002673AA9E500;
  wire al_000002673AA9FBB0;
  wire al_000002673AA9DAB0;
  wire al_000002673AA9DB60;
  wire al_000002673AAA03F0;
  wire al_000002673AA9DD70;
  wire al_000002673AA9F210;
  wire al_000002673AA9F420;
  wire al_000002673AA9F840;
  wire al_000002673AA9F160;
  wire al_000002673AA9DC10;
  wire al_000002673AA9E3A0;
  wire al_000002673AA9E5B0;
  wire al_000002673AA9FFD0;
  wire al_000002673AAA0290;
  wire al_000002673AA9F580;
  wire al_000002673AA9FF20;
  wire al_000002673AAA0080;
  wire al_000002673AA9F0B0;
  wire al_000002673AA9DA00;
  wire al_000002673AA9DCC0;
  wire al_000002673AAA01E0;
  wire al_000002673AA9E710;
  wire al_000002673AA9D8A0;
  wire al_000002673AA9EDF0;
  wire al_000002673A830B20;
  wire al_000002673A82ECE0;
  wire al_000002673A82E290;
  wire al_000002673A82E4A0;
  wire al_000002673A830020;
  wire al_000002673A82FB50;
  wire al_000002673A82E3F0;
  wire al_000002673A82E600;
  wire al_000002673A82E8C0;
  wire al_000002673A82FCB0;
  wire al_000002673A82FEC0;
  wire al_000002673A830390;
  wire al_000002673A831C50;
  wire al_000002673A830D30;
  wire al_000002673A832EE0;
  wire al_000002673A830C80;
  wire al_000002673A533280;
  wire al_000002673A5335F0;
  wire al_000002673A535BC0;
  wire al_000002673A533120;
  wire al_000002673A533B70;
  wire al_000002673A534880;
  wire al_000002673A533330;
  wire al_000002673A534510;
  wire al_000002673A533CD0;
  wire al_000002673A535380;
  wire al_000002673A533D80;
  wire al_000002673A533EE0;
  wire al_000002673A534460;
  wire al_000002673A535430;
  wire al_000002673A534040;
  wire al_000002673A535590;
  wire al_000002673A5340F0;
  wire al_000002673A534A90;
  wire al_000002673A534B40;
  wire al_000002673A5345C0;
  wire al_000002673A534BF0;
  wire al_000002673A534D50;
  wire al_000002673A535640;
  wire al_000002673A5341A0;
  wire al_000002673A534250;
  wire al_000002673A534300;
  wire al_000002673A832AC0;
  wire al_000002673A833D50;
  wire al_000002673A8C95E0;
  wire al_000002673A8C9110;
  wire al_000002673A8C8350;
  wire al_000002673A8C93D0;
  wire al_000002673A8CB2C0;
  wire al_000002673A8CB420;
  wire al_000002673A8CB840;
  wire al_000002673A8CB6E0;
  wire al_000002673A8CCD90;
  wire al_000002673A8CD470;
  wire al_000002673A8CCA20;
  wire al_000002673A8CB790;
  wire al_000002673A8CBF20;
  wire al_000002673A8CC810;
  wire al_000002673A53A550;
  wire al_000002673A53A340;
  wire al_000002673A8CD890;
  wire al_000002673A8D1E00;
  wire al_000002673A8D2F30;
  wire al_000002673A8D2010;
  wire al_000002673A8D4320;
  wire al_000002673A8D50E0;
  wire al_000002673A8D4C10;
  wire al_000002673A8D5BE0;
  wire al_000002673A8D4480;
  wire al_000002673A8D5A80;
  wire al_000002673A8D3FB0;
  wire al_000002673A8D5B30;
  wire al_000002673A702530;
  wire al_000002673A702AB0;

  AL_MAP_LUT5 #(
    .EQN("(~B*~((E*~(D)*~(A)+E*D*~(A)+~(E)*D*A+E*D*A))*~(C)+~B*(E*~(D)*~(A)+E*D*~(A)+~(E)*D*A+E*D*A)*~(C)+~(~B)*(E*~(D)*~(A)+E*D*~(A)+~(E)*D*A+E*D*A)*C+~B*(E*~(D)*~(A)+E*D*~(A)+~(E)*D*A+E*D*A)*C)"),
    .INIT(32'hf353a303))
    al_000002673AACD8D0 (
    .a(al_000002673AA9F0B0),
    .b(al_000002673AA9DD70),
    .c(al_000002673A8A4BD0[0]),
    .d(al_000002673A8AAAC0[0]),
    .e(txd),
    .o(al_000002673AA5F070));
  AL_MAP_LUT2 #(
    .EQN("(~B*~A)"),
    .INIT(4'h1))
    al_000002673AACB070 (
    .a(al_000002673AA9F840),
    .b(txd),
    .o(al_000002673AA9DE20));
  AL_MAP_LUT5 #(
    .EQN("~((~B*~(A)*~(D)+~B*A*~(D)+~(~B)*A*D+~B*A*D)*~(C)*~(E)+(~B*~(A)*~(D)+~B*A*~(D)+~(~B)*A*D+~B*A*D)*C*~(E)+~((~B*~(A)*~(D)+~B*A*~(D)+~(~B)*A*D+~B*A*D))*C*E+(~B*~(A)*~(D)+~B*A*~(D)+~(~B)*A*D+~B*A*D)*C*E)"),
    .INIT(32'h0f0f55cc))
    al_000002673AACDD10 (
    .a(al_000002673AA9EDF0),
    .b(al_000002673AA5F070),
    .c(al_000002673AA9DE20),
    .d(al_000002673A8A4BD0[1]),
    .e(al_000002673A8A4BD0[2]),
    .o(al_000002673A8D50E0));
  AL_MAP_LUT5 #(
    .EQN("(~E*~(~(C*~B)*~(A)*~(D)+~(C*~B)*A*~(D)+~(~(C*~B))*A*D+~(C*~B)*A*D))"),
    .INIT(32'h00005530))
    al_000002673AACAB20 (
    .a(al_000002673AAA0080),
    .b(al_000002673A8A68B0[0]),
    .c(al_000002673AA9F210),
    .d(al_000002673A8A4BD0[1]),
    .e(al_000002673A8A4BD0[2]),
    .o(al_000002673A8A5F10[1]));
  AL_MAP_LUT5 #(
    .EQN("(A*B*C*~(D)*~(E)+~(A)*B*~(C)*D*~(E)+A*B*~(C)*D*~(E)+A*B*C*D*~(E)+~(A)*~(B)*C*~(D)*E+A*~(B)*C*~(D)*E+A*B*C*~(D)*E+~(A)*~(B)*~(C)*D*E+A*~(B)*~(C)*D*E+A*B*~(C)*D*E+~(A)*~(B)*C*D*E+A*~(B)*C*D*E+A*B*C*D*E)"),
    .INIT(32'hbbb08c80))
    al_000002673AACC6C0 (
    .a(al_000002673A8A68B0[0]),
    .b(al_000002673A702AB0),
    .c(al_000002673A8A4BD0[0]),
    .d(al_000002673A8A4BD0[1]),
    .e(al_000002673A8A8980[0]),
    .o(al_000002673AA5D780));
  AL_MAP_LUT5 #(
    .EQN("(A*~((E*~(B)*~(C)+E*B*~(C)+~(E)*B*C+E*B*C))*~(D)+A*(E*~(B)*~(C)+E*B*~(C)+~(E)*B*C+E*B*C)*~(D)+~(A)*(E*~(B)*~(C)+E*B*~(C)+~(E)*B*C+E*B*C)*D+A*(E*~(B)*~(C)+E*B*~(C)+~(E)*B*C+E*B*C)*D)"),
    .INIT(32'hcfaac0aa))
    al_000002673AACA6E0 (
    .a(al_000002673AA5D780),
    .b(al_000002673A8A68B0[0]),
    .c(al_000002673AA9F840),
    .d(al_000002673A8A4BD0[2]),
    .e(al_000002673A8A8980[0]),
    .o(al_000002673A8A8670[0]));
  AL_MAP_LUT5 #(
    .EQN("(A*~(~(E*~C)*~(B)*~(D)+~(E*~C)*B*~(D)+~(~(E*~C))*B*D+~(E*~C)*B*D))"),
    .INIT(32'h220a2200))
    al_000002673AACC170 (
    .a(al_000002673A702530),
    .b(al_000002673A8C8350),
    .c(al_000002673A8C93D0),
    .d(al_000002673A55C970[0]),
    .e(al_000002673A55C970[1]),
    .o(al_000002673AA9F2C0));
  AL_MAP_LUT4 #(
    .EQN("(~(D*~B)*~(C*A))"),
    .INIT(16'h4c5f))
    al_000002673AACB7E0 (
    .a(al_000002673AA9F2C0),
    .b(al_000002673A702530),
    .c(al_000002673A897880[7]),
    .d(al_000002673A55CB30[7]),
    .o(al_000002673AA9DED0));
  AL_MAP_LUT3 #(
    .EQN("(~C*B*~A)"),
    .INIT(8'h04))
    al_000002673AACD7C0 (
    .a(al_000002673AA9E5B0),
    .b(al_000002673AA9FBB0),
    .c(al_000002673A8C8350),
    .o(al_000002673AA9E870));
  AL_MAP_LUT2 #(
    .EQN("(B*~A)"),
    .INIT(4'h4))
    al_000002673AACC280 (
    .a(al_000002673AA9FBB0),
    .b(al_000002673A55CB30[7]),
    .o(al_000002673AA9D950));
  AL_MAP_LUT5 #(
    .EQN("~(A*~((~C*~(D*B)))*~(E)+A*(~C*~(D*B))*~(E)+~(A)*(~C*~(D*B))*E+A*(~C*~(D*B))*E)"),
    .INIT(32'hfcf05555))
    al_000002673AACD9E0 (
    .a(al_000002673AA9DED0),
    .b(al_000002673AA9E870),
    .c(al_000002673AA9D950),
    .d(al_000002673A897880[7]),
    .e(al_000002673A55C970[2]),
    .o(al_000002673A899100[7]));
  AL_MAP_LUT4 #(
    .EQN("(~(D*~B)*~(C*A))"),
    .INIT(16'h4c5f))
    al_000002673AACB3A0 (
    .a(al_000002673AA9F2C0),
    .b(al_000002673A702530),
    .c(al_000002673A897880[6]),
    .d(al_000002673A55CB30[6]),
    .o(al_000002673AA9F370));
  AL_MAP_LUT2 #(
    .EQN("(B*~A)"),
    .INIT(4'h4))
    al_000002673AACB6D0 (
    .a(al_000002673AA9FBB0),
    .b(al_000002673A55CB30[6]),
    .o(al_000002673AA9F8F0));
  AL_MAP_LUT5 #(
    .EQN("~(A*~((~C*~(D*B)))*~(E)+A*(~C*~(D*B))*~(E)+~(A)*(~C*~(D*B))*E+A*(~C*~(D*B))*E)"),
    .INIT(32'hfcf05555))
    al_000002673AACA7F0 (
    .a(al_000002673AA9F370),
    .b(al_000002673AA9E870),
    .c(al_000002673AA9F8F0),
    .d(al_000002673A897880[6]),
    .e(al_000002673A55C970[2]),
    .o(al_000002673A899100[6]));
  AL_MAP_LUT4 #(
    .EQN("(~(D*~B)*~(C*A))"),
    .INIT(16'h4c5f))
    al_000002673AACB4B0 (
    .a(al_000002673AA9F2C0),
    .b(al_000002673A702530),
    .c(al_000002673A897880[5]),
    .d(al_000002673A55CB30[5]),
    .o(al_000002673AA9FA50));
  AL_MAP_LUT2 #(
    .EQN("(B*~A)"),
    .INIT(4'h4))
    al_000002673AACAA10 (
    .a(al_000002673AA9FBB0),
    .b(al_000002673A55CB30[5]),
    .o(al_000002673AA9F4D0));
  AL_MAP_LUT5 #(
    .EQN("~(A*~((~C*~(D*B)))*~(E)+A*(~C*~(D*B))*~(E)+~(A)*(~C*~(D*B))*E+A*(~C*~(D*B))*E)"),
    .INIT(32'hfcf05555))
    al_000002673AACC390 (
    .a(al_000002673AA9FA50),
    .b(al_000002673AA9E870),
    .c(al_000002673AA9F4D0),
    .d(al_000002673A897880[5]),
    .e(al_000002673A55C970[2]),
    .o(al_000002673A899100[5]));
  AL_MAP_LUT4 #(
    .EQN("(~(D*~B)*~(C*A))"),
    .INIT(16'h4c5f))
    al_000002673AACBA00 (
    .a(al_000002673AA9F2C0),
    .b(al_000002673A702530),
    .c(al_000002673A897880[4]),
    .d(al_000002673A55CB30[4]),
    .o(al_000002673AA9F630));
  AL_MAP_LUT2 #(
    .EQN("(B*~A)"),
    .INIT(4'h4))
    al_000002673AACCC10 (
    .a(al_000002673AA9FBB0),
    .b(al_000002673A55CB30[4]),
    .o(al_000002673AAA0340));
  AL_MAP_LUT5 #(
    .EQN("~(A*~((~C*~(D*B)))*~(E)+A*(~C*~(D*B))*~(E)+~(A)*(~C*~(D*B))*E+A*(~C*~(D*B))*E)"),
    .INIT(32'hfcf05555))
    al_000002673AACC8E0 (
    .a(al_000002673AA9F630),
    .b(al_000002673AA9E870),
    .c(al_000002673AAA0340),
    .d(al_000002673A897880[4]),
    .e(al_000002673A55C970[2]),
    .o(al_000002673A899100[4]));
  AL_MAP_LUT4 #(
    .EQN("(~(D*~B)*~(C*A))"),
    .INIT(16'h4c5f))
    al_000002673AACCE30 (
    .a(al_000002673AA9F2C0),
    .b(al_000002673A702530),
    .c(al_000002673A897880[3]),
    .d(al_000002673A55CB30[3]),
    .o(al_000002673AA9E240));
  AL_MAP_LUT2 #(
    .EQN("(B*~A)"),
    .INIT(4'h4))
    al_000002673AACC9F0 (
    .a(al_000002673AA9FBB0),
    .b(al_000002673A55CB30[3]),
    .o(al_000002673AA9F9A0));
  AL_MAP_LUT5 #(
    .EQN("~(A*~((~C*~(D*B)))*~(E)+A*(~C*~(D*B))*~(E)+~(A)*(~C*~(D*B))*E+A*(~C*~(D*B))*E)"),
    .INIT(32'hfcf05555))
    al_000002673AACD270 (
    .a(al_000002673AA9E240),
    .b(al_000002673AA9E870),
    .c(al_000002673AA9F9A0),
    .d(al_000002673A897880[3]),
    .e(al_000002673A55C970[2]),
    .o(al_000002673A899100[3]));
  AL_MAP_LUT4 #(
    .EQN("(~(D*~B)*~(C*A))"),
    .INIT(16'h4c5f))
    al_000002673AACD380 (
    .a(al_000002673AA9F2C0),
    .b(al_000002673A702530),
    .c(al_000002673A897880[2]),
    .d(al_000002673A55CB30[2]),
    .o(al_000002673AA9F000));
  AL_MAP_LUT2 #(
    .EQN("(B*~A)"),
    .INIT(4'h4))
    al_000002673AACE7B0 (
    .a(al_000002673AA9FBB0),
    .b(al_000002673A55CB30[2]),
    .o(al_000002673AA9FB00));
  AL_MAP_LUT5 #(
    .EQN("~(A*~((~C*~(D*B)))*~(E)+A*(~C*~(D*B))*~(E)+~(A)*(~C*~(D*B))*E+A*(~C*~(D*B))*E)"),
    .INIT(32'hfcf05555))
    al_000002673AACF580 (
    .a(al_000002673AA9F000),
    .b(al_000002673AA9E870),
    .c(al_000002673AA9FB00),
    .d(al_000002673A897880[2]),
    .e(al_000002673A55C970[2]),
    .o(al_000002673A899100[2]));
  AL_MAP_LUT4 #(
    .EQN("(~(D*~B)*~(C*A))"),
    .INIT(16'h4c5f))
    al_000002673AAD2220 (
    .a(al_000002673AA9F2C0),
    .b(al_000002673A702530),
    .c(al_000002673A897880[1]),
    .d(al_000002673A55CB30[1]),
    .o(al_000002673AA9E7C0));
  AL_MAP_LUT2 #(
    .EQN("(B*~A)"),
    .INIT(4'h4))
    al_000002673AACE480 (
    .a(al_000002673AA9FBB0),
    .b(al_000002673A55CB30[1]),
    .o(al_000002673AA9DF80));
  AL_MAP_LUT5 #(
    .EQN("~(A*~((~C*~(D*B)))*~(E)+A*(~C*~(D*B))*~(E)+~(A)*(~C*~(D*B))*E+A*(~C*~(D*B))*E)"),
    .INIT(32'hfcf05555))
    al_000002673AAD0680 (
    .a(al_000002673AA9E7C0),
    .b(al_000002673AA9E870),
    .c(al_000002673AA9DF80),
    .d(al_000002673A897880[1]),
    .e(al_000002673A55C970[2]),
    .o(al_000002673A899100[1]));
  AL_MAP_LUT4 #(
    .EQN("(~(D*~B)*~(C*A))"),
    .INIT(16'h4c5f))
    al_000002673AAD0DF0 (
    .a(al_000002673AA9F2C0),
    .b(al_000002673A702530),
    .c(al_000002673A897880[0]),
    .d(al_000002673A55CB30[0]),
    .o(al_000002673AA9E920));
  AL_MAP_LUT2 #(
    .EQN("(B*~A)"),
    .INIT(4'h4))
    al_000002673AAD0020 (
    .a(al_000002673AA9FBB0),
    .b(al_000002673A55CB30[0]),
    .o(al_000002673AA9F6E0));
  AL_MAP_LUT5 #(
    .EQN("~(A*~((~C*~(D*B)))*~(E)+A*(~C*~(D*B))*~(E)+~(A)*(~C*~(D*B))*E+A*(~C*~(D*B))*E)"),
    .INIT(32'hfcf05555))
    al_000002673AACE590 (
    .a(al_000002673AA9E920),
    .b(al_000002673AA9E870),
    .c(al_000002673AA9F6E0),
    .d(al_000002673A897880[0]),
    .e(al_000002673A55C970[2]),
    .o(al_000002673A899100[0]));
  AL_MAP_LUT3 #(
    .EQN("(B*~(~C*~A))"),
    .INIT(8'hc8))
    al_000002673AAD1340 (
    .a(al_000002673AA9E5B0),
    .b(al_000002673A702530),
    .c(al_000002673A8C8350),
    .o(al_000002673AA9FC60));
  AL_MAP_LUT5 #(
    .EQN("(D*(B*~((C*~A))*~(E)+B*(C*~A)*~(E)+~(B)*(C*~A)*E+B*(C*~A)*E))"),
    .INIT(32'h5000cc00))
    al_000002673AACF690 (
    .a(al_000002673AA9FC60),
    .b(al_000002673AA5BBF0),
    .c(al_000002673AA9E3A0),
    .d(rst_n),
    .e(al_000002673A55C970[2]),
    .o(al_000002673A8988B0[2]));
  AL_MAP_LUT4 #(
    .EQN("(D*~C*B*~A)"),
    .INIT(16'h0400))
    al_000002673AACED00 (
    .a(al_000002673AA9FF20),
    .b(al_000002673A702AB0),
    .c(al_000002673A8A4BD0[0]),
    .d(al_000002673A8A8980[0]),
    .o(al_000002673AA9E030));
  AL_MAP_LUT3 #(
    .EQN("(B*~(C)*~(A)+B*C*~(A)+~(B)*C*A+B*C*A)"),
    .INIT(8'he4))
    al_000002673AAD1670 (
    .a(al_000002673AA9E030),
    .b(al_000002673A8AAAC0[1]),
    .c(al_000002673A8AAAC0[2]),
    .o(al_000002673AA63600));
  AL_MAP_LUT3 #(
    .EQN("(B*~(A)*~(C)+B*A*~(C)+~(B)*A*C+B*A*C)"),
    .INIT(8'hac))
    al_000002673AACF7A0 (
    .a(al_000002673A8AA190[1]),
    .b(al_000002673A8AAAC0[1]),
    .c(al_000002673AA9DD70),
    .o(al_000002673A8A7020[1]));
  AL_MAP_LUT5 #(
    .EQN("(A*~((D*~(E)*~(B)+D*E*~(B)+~(D)*E*B+D*E*B))*~(C)+A*(D*~(E)*~(B)+D*E*~(B)+~(D)*E*B+D*E*B)*~(C)+~(A)*(D*~(E)*~(B)+D*E*~(B)+~(D)*E*B+D*E*B)*C+A*(D*~(E)*~(B)+D*E*~(B)+~(D)*E*B+D*E*B)*C)"),
    .INIT(32'hfaca3a0a))
    al_000002673AAD1780 (
    .a(al_000002673A8A7020[1]),
    .b(al_000002673AA9F0B0),
    .c(al_000002673A8A4BD0[0]),
    .d(al_000002673A8AAAC0[1]),
    .e(al_000002673A8AAAC0[2]),
    .o(al_000002673AA60730));
  AL_MAP_LUT5 #(
    .EQN("((B*~(A)*~(C)+B*A*~(C)+~(B)*A*C+B*A*C)*~(E)*~(D)+(B*~(A)*~(C)+B*A*~(C)+~(B)*A*C+B*A*C)*E*~(D)+~((B*~(A)*~(C)+B*A*~(C)+~(B)*A*C+B*A*C))*E*D+(B*~(A)*~(C)+B*A*~(C)+~(B)*A*C+B*A*C)*E*D)"),
    .INIT(32'hffac00ac))
    al_000002673AAD62F0 (
    .a(al_000002673AA63600),
    .b(al_000002673AA60730),
    .c(al_000002673A8A4BD0[1]),
    .d(al_000002673A8A4BD0[2]),
    .e(al_000002673A8AAAC0[1]),
    .o(al_000002673A8A86E0[1]));
  AL_MAP_LUT5 #(
    .EQN("(~(A)*~(B)*~(C)*~(D)*~(E)+A*~(B)*~(C)*~(D)*~(E)+~(A)*~(B)*~(C)*D*~(E)+A*~(B)*~(C)*D*~(E)+~(A)*B*~(C)*D*~(E)+~(A)*~(B)*C*D*~(E)+A*~(B)*C*D*~(E)+~(A)*B*C*D*~(E)+A*B*C*D*~(E)+~(A)*~(B)*~(C)*~(D)*E+A*~(B)*~(C)*~(D)*E+A*B*~(C)*~(D)*E+~(A)*~(B)*~(C)*D*E+A*~(B)*~(C)*D*E+~(A)*B*~(C)*D*E+A*B*~(C)*D*E+~(A)*~(B)*C*D*E+A*~(B)*C*D*E+~(A)*B*C*D*E+A*B*C*D*E)"),
    .INIT(32'hff0bf703))
    al_000002673AAD2DD0 (
    .a(al_000002673AA9E030),
    .b(al_000002673A8A4BD0[1]),
    .c(al_000002673A8A4BD0[2]),
    .d(al_000002673A8AAAC0[0]),
    .e(al_000002673A8AAAC0[1]),
    .o(al_000002673AA9E0E0));
  AL_MAP_LUT4 #(
    .EQN("(B*~(C*~(D)*~(A)+C*D*~(A)+~(C)*D*A+C*D*A))"),
    .INIT(16'h048c))
    al_000002673AAD5740 (
    .a(al_000002673AA9F0B0),
    .b(al_000002673A8A4BD0[0]),
    .c(al_000002673A8AAAC0[0]),
    .d(al_000002673A8AAAC0[1]),
    .o(al_000002673AA9F790));
  AL_MAP_LUT4 #(
    .EQN("(~C*~(D*~(B)*~(A)+D*B*~(A)+~(D)*B*A+D*B*A))"),
    .INIT(16'h0207))
    al_000002673AAD5C90 (
    .a(al_000002673AA9DD70),
    .b(al_000002673A8AA190[0]),
    .c(al_000002673A8A4BD0[0]),
    .d(al_000002673A8AAAC0[0]),
    .o(al_000002673AA9FD10));
  AL_MAP_LUT5 #(
    .EQN("(A*~(~E*~D*~(~C*~B)))"),
    .INIT(32'haaaaaa02))
    al_000002673AAD6B70 (
    .a(al_000002673AA9E0E0),
    .b(al_000002673AA9F790),
    .c(al_000002673AA9FD10),
    .d(al_000002673A8A4BD0[1]),
    .e(al_000002673A8A4BD0[2]),
    .o(al_000002673A8A86E0[0]));
  AL_MAP_LUT5 #(
    .EQN("(~(A)*~(B)*~(C)*~(D)*~(E)+A*~(B)*~(C)*~(D)*~(E)+~(A)*B*~(C)*~(D)*~(E)+A*B*~(C)*~(D)*~(E)+~(A)*~(B)*C*~(D)*~(E)+A*~(B)*C*~(D)*~(E)+~(A)*~(B)*~(C)*D*~(E)+A*~(B)*~(C)*D*~(E)+~(A)*B*~(C)*D*~(E)+A*B*~(C)*D*~(E)+~(A)*~(B)*C*D*~(E)+A*~(B)*C*D*~(E)+~(A)*B*C*D*~(E)+A*B*C*D*~(E)+~(A)*B*~(C)*~(D)*E+A*B*~(C)*~(D)*E+A*~(B)*~(C)*D*E+A*B*~(C)*D*E+A*~(B)*C*D*E+A*B*C*D*E)"),
    .INIT(32'haa0cff3f))
    al_000002673AAD2BB0 (
    .a(al_000002673AA9F0B0),
    .b(al_000002673AA9DD70),
    .c(al_000002673A8AA190[7]),
    .d(al_000002673A8A4BD0[0]),
    .e(al_000002673A8AAAC0[7]),
    .o(al_000002673AA9FDC0));
  AL_MAP_LUT5 #(
    .EQN("(~(A)*~(B)*~(C)*~(D)*~(E)+~(A)*B*~(C)*~(D)*~(E)+~(A)*~(B)*~(C)*~(D)*E+~(A)*B*~(C)*~(D)*E+~(A)*~(B)*C*~(D)*E+A*~(B)*C*~(D)*E+~(A)*~(B)*~(C)*D*E+A*~(B)*~(C)*D*E+~(A)*B*~(C)*D*E+A*B*~(C)*D*E+~(A)*~(B)*C*D*E+A*~(B)*C*D*E+~(A)*B*C*D*E+A*B*C*D*E)"),
    .INIT(32'hff350005))
    al_000002673AAD4860 (
    .a(al_000002673AA9FDC0),
    .b(al_000002673AA9E030),
    .c(al_000002673A8A4BD0[1]),
    .d(al_000002673A8A4BD0[2]),
    .e(al_000002673A8AAAC0[7]),
    .o(al_000002673A8A86E0[7]));
  AL_MAP_LUT5 #(
    .EQN("(~(A)*~(B)*~(C)*~(D)*~(E)+A*~(B)*~(C)*~(D)*~(E)+~(A)*~(B)*~(C)*D*~(E)+A*~(B)*~(C)*D*~(E)+~(A)*B*~(C)*D*~(E)+~(A)*~(B)*C*D*~(E)+A*~(B)*C*D*~(E)+~(A)*B*C*D*~(E)+A*B*C*D*~(E)+~(A)*~(B)*~(C)*~(D)*E+A*~(B)*~(C)*~(D)*E+A*B*~(C)*~(D)*E+~(A)*~(B)*~(C)*D*E+A*~(B)*~(C)*D*E+~(A)*B*~(C)*D*E+A*B*~(C)*D*E+~(A)*~(B)*C*D*E+A*~(B)*C*D*E+~(A)*B*C*D*E+A*B*C*D*E)"),
    .INIT(32'hff0bf703))
    al_000002673AAD5960 (
    .a(al_000002673AA9E030),
    .b(al_000002673A8A4BD0[1]),
    .c(al_000002673A8A4BD0[2]),
    .d(al_000002673A8AAAC0[6]),
    .e(al_000002673A8AAAC0[7]),
    .o(al_000002673AA9E190));
  AL_MAP_LUT4 #(
    .EQN("(B*~(C*~(D)*~(A)+C*D*~(A)+~(C)*D*A+C*D*A))"),
    .INIT(16'h048c))
    al_000002673AAD3100 (
    .a(al_000002673AA9F0B0),
    .b(al_000002673A8A4BD0[0]),
    .c(al_000002673A8AAAC0[6]),
    .d(al_000002673A8AAAC0[7]),
    .o(al_000002673AA9EA80));
  AL_MAP_LUT4 #(
    .EQN("(~C*~(D*~(B)*~(A)+D*B*~(A)+~(D)*B*A+D*B*A))"),
    .INIT(16'h0207))
    al_000002673AAD4530 (
    .a(al_000002673AA9DD70),
    .b(al_000002673A8AA190[6]),
    .c(al_000002673A8A4BD0[0]),
    .d(al_000002673A8AAAC0[6]),
    .o(al_000002673AA9E9D0));
  AL_MAP_LUT5 #(
    .EQN("(A*~(~E*~D*~(~C*~B)))"),
    .INIT(32'haaaaaa02))
    al_000002673AAD4640 (
    .a(al_000002673AA9E190),
    .b(al_000002673AA9EA80),
    .c(al_000002673AA9E9D0),
    .d(al_000002673A8A4BD0[1]),
    .e(al_000002673A8A4BD0[2]),
    .o(al_000002673A8A86E0[6]));
  AL_MAP_LUT5 #(
    .EQN("(~(A)*~(B)*~(C)*~(D)*~(E)+A*~(B)*~(C)*~(D)*~(E)+~(A)*~(B)*~(C)*D*~(E)+A*~(B)*~(C)*D*~(E)+~(A)*B*~(C)*D*~(E)+~(A)*~(B)*C*D*~(E)+A*~(B)*C*D*~(E)+~(A)*B*C*D*~(E)+A*B*C*D*~(E)+~(A)*~(B)*~(C)*~(D)*E+A*~(B)*~(C)*~(D)*E+A*B*~(C)*~(D)*E+~(A)*~(B)*~(C)*D*E+A*~(B)*~(C)*D*E+~(A)*B*~(C)*D*E+A*B*~(C)*D*E+~(A)*~(B)*C*D*E+A*~(B)*C*D*E+~(A)*B*C*D*E+A*B*C*D*E)"),
    .INIT(32'hff0bf703))
    al_000002673AAD6510 (
    .a(al_000002673AA9E030),
    .b(al_000002673A8A4BD0[1]),
    .c(al_000002673A8A4BD0[2]),
    .d(al_000002673A8AAAC0[5]),
    .e(al_000002673A8AAAC0[6]),
    .o(al_000002673AA9EB30));
  AL_MAP_LUT4 #(
    .EQN("(B*~(C*~(D)*~(A)+C*D*~(A)+~(C)*D*A+C*D*A))"),
    .INIT(16'h048c))
    al_000002673AAD3A90 (
    .a(al_000002673AA9F0B0),
    .b(al_000002673A8A4BD0[0]),
    .c(al_000002673A8AAAC0[5]),
    .d(al_000002673A8AAAC0[6]),
    .o(al_000002673AA9EBE0));
  AL_MAP_LUT4 #(
    .EQN("(~C*~(D*~(B)*~(A)+D*B*~(A)+~(D)*B*A+D*B*A))"),
    .INIT(16'h0207))
    al_000002673AAD3320 (
    .a(al_000002673AA9DD70),
    .b(al_000002673A8AA190[5]),
    .c(al_000002673A8A4BD0[0]),
    .d(al_000002673A8AAAC0[5]),
    .o(al_000002673AA9EC90));
  AL_MAP_LUT5 #(
    .EQN("(A*~(~E*~D*~(~C*~B)))"),
    .INIT(32'haaaaaa02))
    al_000002673AAD5EB0 (
    .a(al_000002673AA9EB30),
    .b(al_000002673AA9EBE0),
    .c(al_000002673AA9EC90),
    .d(al_000002673A8A4BD0[1]),
    .e(al_000002673A8A4BD0[2]),
    .o(al_000002673A8A86E0[5]));
  AL_MAP_LUT5 #(
    .EQN("(~(A)*~(B)*~(C)*~(D)*~(E)+A*~(B)*~(C)*~(D)*~(E)+~(A)*~(B)*~(C)*D*~(E)+A*~(B)*~(C)*D*~(E)+~(A)*B*~(C)*D*~(E)+~(A)*~(B)*C*D*~(E)+A*~(B)*C*D*~(E)+~(A)*B*C*D*~(E)+A*B*C*D*~(E)+~(A)*~(B)*~(C)*~(D)*E+A*~(B)*~(C)*~(D)*E+A*B*~(C)*~(D)*E+~(A)*~(B)*~(C)*D*E+A*~(B)*~(C)*D*E+~(A)*B*~(C)*D*E+A*B*~(C)*D*E+~(A)*~(B)*C*D*E+A*~(B)*C*D*E+~(A)*B*C*D*E+A*B*C*D*E)"),
    .INIT(32'hff0bf703))
    al_000002673AAD5DA0 (
    .a(al_000002673AA9E030),
    .b(al_000002673A8A4BD0[1]),
    .c(al_000002673A8A4BD0[2]),
    .d(al_000002673A8AAAC0[4]),
    .e(al_000002673A8AAAC0[5]),
    .o(al_000002673AA9EEA0));
  AL_MAP_LUT4 #(
    .EQN("(B*~(C*~(D)*~(A)+C*D*~(A)+~(C)*D*A+C*D*A))"),
    .INIT(16'h048c))
    al_000002673AAD5A70 (
    .a(al_000002673AA9F0B0),
    .b(al_000002673A8A4BD0[0]),
    .c(al_000002673A8AAAC0[4]),
    .d(al_000002673A8AAAC0[5]),
    .o(al_000002673AA9EF50));
  AL_MAP_LUT4 #(
    .EQN("(~C*~(D*~(B)*~(A)+D*B*~(A)+~(D)*B*A+D*B*A))"),
    .INIT(16'h0207))
    al_000002673AAD6620 (
    .a(al_000002673AA9DD70),
    .b(al_000002673A8AA190[4]),
    .c(al_000002673A8A4BD0[0]),
    .d(al_000002673A8AAAC0[4]),
    .o(al_000002673AAA1AA0));
  AL_MAP_LUT5 #(
    .EQN("(A*~(~E*~D*~(~C*~B)))"),
    .INIT(32'haaaaaa02))
    al_000002673AAD6730 (
    .a(al_000002673AA9EEA0),
    .b(al_000002673AA9EF50),
    .c(al_000002673AAA1AA0),
    .d(al_000002673A8A4BD0[1]),
    .e(al_000002673A8A4BD0[2]),
    .o(al_000002673A8A86E0[4]));
  AL_MAP_LUT5 #(
    .EQN("(~(A)*~(B)*~(C)*~(D)*~(E)+A*~(B)*~(C)*~(D)*~(E)+~(A)*~(B)*~(C)*D*~(E)+A*~(B)*~(C)*D*~(E)+~(A)*B*~(C)*D*~(E)+~(A)*~(B)*C*D*~(E)+A*~(B)*C*D*~(E)+~(A)*B*C*D*~(E)+A*B*C*D*~(E)+~(A)*~(B)*~(C)*~(D)*E+A*~(B)*~(C)*~(D)*E+A*B*~(C)*~(D)*E+~(A)*~(B)*~(C)*D*E+A*~(B)*~(C)*D*E+~(A)*B*~(C)*D*E+A*B*~(C)*D*E+~(A)*~(B)*C*D*E+A*~(B)*C*D*E+~(A)*B*C*D*E+A*B*C*D*E)"),
    .INIT(32'hff0bf703))
    al_000002673AAD6840 (
    .a(al_000002673AA9E030),
    .b(al_000002673A8A4BD0[1]),
    .c(al_000002673A8A4BD0[2]),
    .d(al_000002673A8AAAC0[3]),
    .e(al_000002673A8AAAC0[4]),
    .o(al_000002673AAA1100));
  AL_MAP_LUT4 #(
    .EQN("(B*~(C*~(D)*~(A)+C*D*~(A)+~(C)*D*A+C*D*A))"),
    .INIT(16'h048c))
    al_000002673AAD3CB0 (
    .a(al_000002673AA9F0B0),
    .b(al_000002673A8A4BD0[0]),
    .c(al_000002673A8AAAC0[3]),
    .d(al_000002673A8AAAC0[4]),
    .o(al_000002673AAA22E0));
  AL_MAP_LUT4 #(
    .EQN("(~C*~(D*~(B)*~(A)+D*B*~(A)+~(D)*B*A+D*B*A))"),
    .INIT(16'h0207))
    al_000002673A87A000 (
    .a(al_000002673AA9DD70),
    .b(al_000002673A8AA190[3]),
    .c(al_000002673A8A4BD0[0]),
    .d(al_000002673A8AAAC0[3]),
    .o(al_000002673AAA1940));
  AL_MAP_LUT5 #(
    .EQN("(A*~(~E*~D*~(~C*~B)))"),
    .INIT(32'haaaaaa02))
    al_000002673A8779C0 (
    .a(al_000002673AAA1100),
    .b(al_000002673AAA22E0),
    .c(al_000002673AAA1940),
    .d(al_000002673A8A4BD0[1]),
    .e(al_000002673A8A4BD0[2]),
    .o(al_000002673A8A86E0[3]));
  AL_MAP_LUT5 #(
    .EQN("(~(A)*~(B)*~(C)*~(D)*~(E)+A*~(B)*~(C)*~(D)*~(E)+~(A)*~(B)*~(C)*D*~(E)+A*~(B)*~(C)*D*~(E)+~(A)*B*~(C)*D*~(E)+~(A)*~(B)*C*D*~(E)+A*~(B)*C*D*~(E)+~(A)*B*C*D*~(E)+A*B*C*D*~(E)+~(A)*~(B)*~(C)*~(D)*E+A*~(B)*~(C)*~(D)*E+A*B*~(C)*~(D)*E+~(A)*~(B)*~(C)*D*E+A*~(B)*~(C)*D*E+~(A)*B*~(C)*D*E+A*B*~(C)*D*E+~(A)*~(B)*C*D*E+A*~(B)*C*D*E+~(A)*B*C*D*E+A*B*C*D*E)"),
    .INIT(32'hff0bf703))
    al_000002673A878CE0 (
    .a(al_000002673AA9E030),
    .b(al_000002673A8A4BD0[1]),
    .c(al_000002673A8A4BD0[2]),
    .d(al_000002673A8AAAC0[2]),
    .e(al_000002673A8AAAC0[3]),
    .o(al_000002673AAA1F70));
  AL_MAP_LUT4 #(
    .EQN("(B*~(C*~(D)*~(A)+C*D*~(A)+~(C)*D*A+C*D*A))"),
    .INIT(16'h048c))
    al_000002673A877360 (
    .a(al_000002673AA9F0B0),
    .b(al_000002673A8A4BD0[0]),
    .c(al_000002673A8AAAC0[2]),
    .d(al_000002673A8AAAC0[3]),
    .o(al_000002673AAA0A20));
  AL_MAP_LUT4 #(
    .EQN("(~C*~(D*~(B)*~(A)+D*B*~(A)+~(D)*B*A+D*B*A))"),
    .INIT(16'h0207))
    al_000002673A879450 (
    .a(al_000002673AA9DD70),
    .b(al_000002673A8AA190[2]),
    .c(al_000002673A8A4BD0[0]),
    .d(al_000002673A8AAAC0[2]),
    .o(al_000002673AAA0760));
  AL_MAP_LUT5 #(
    .EQN("(A*~(~E*~D*~(~C*~B)))"),
    .INIT(32'haaaaaa02))
    al_000002673A879560 (
    .a(al_000002673AAA1F70),
    .b(al_000002673AAA0A20),
    .c(al_000002673AAA0760),
    .d(al_000002673A8A4BD0[1]),
    .e(al_000002673A8A4BD0[2]),
    .o(al_000002673A8A86E0[2]));
  AL_MAP_LUT1 #(
    .EQN("(~A)"),
    .INIT(2'h1))
    al_000002673A87B650 (
    .a(al_000002673A54CDE0[0]),
    .o(al_000002673A54FF50[0]));
  AL_MAP_LUT2 #(
    .EQN("(~B*A)"),
    .INIT(4'h2))
    al_000002673AAD7B60 (
    .a(al_000002673A54F770[5]),
    .b(al_000002673A830D30),
    .o(al_000002673A54F2A0[5]));
  AL_MAP_LUT2 #(
    .EQN("(~B*A)"),
    .INIT(4'h2))
    al_000002673AAD81C0 (
    .a(al_000002673A54F770[4]),
    .b(al_000002673A830D30),
    .o(al_000002673A54F2A0[4]));
  AL_MAP_LUT2 #(
    .EQN("(~B*A)"),
    .INIT(4'h2))
    al_000002673AAD92C0 (
    .a(al_000002673A54F770[3]),
    .b(al_000002673A830D30),
    .o(al_000002673A54F2A0[3]));
  AL_MAP_LUT2 #(
    .EQN("(~B*A)"),
    .INIT(4'h2))
    al_000002673AAD9C50 (
    .a(al_000002673A54F770[2]),
    .b(al_000002673A830D30),
    .o(al_000002673A54F2A0[2]));
  AL_MAP_LUT2 #(
    .EQN("(~B*A)"),
    .INIT(4'h2))
    al_000002673AAD9920 (
    .a(al_000002673A54F770[1]),
    .b(al_000002673A830D30),
    .o(al_000002673A54F2A0[1]));
  AL_MAP_LUT2 #(
    .EQN("(~B*A)"),
    .INIT(4'h2))
    al_000002673AAD7940 (
    .a(al_000002673A54F770[0]),
    .b(al_000002673A830D30),
    .o(al_000002673A54F2A0[0]));
  AL_MAP_LUT2 #(
    .EQN("(B@A)"),
    .INIT(4'h6))
    al_000002673AAD6C80 (
    .a(al_000002673A54CDE0[0]),
    .b(al_000002673A54CDE0[1]),
    .o(al_000002673A54FF50[1]));
  AL_MAP_LUT2 #(
    .EQN("~(~B*~A)"),
    .INIT(4'he))
    al_000002673AAD9D60 (
    .a(al_000002673A8CCD90),
    .b(al_000002673A8CC810),
    .o(rx_err));
  AL_MAP_LUT2 #(
    .EQN("(B*A)"),
    .INIT(4'h8))
    al_000002673AAD7A50 (
    .a(tx_en),
    .b(tx_rdy),
    .o(al_000002673A8D1E00));
  AL_MAP_LUT3 #(
    .EQN("(C@(B*A))"),
    .INIT(8'h78))
    al_000002673AAD95F0 (
    .a(al_000002673A54CDE0[0]),
    .b(al_000002673A54CDE0[1]),
    .c(al_000002673A54CDE0[2]),
    .o(al_000002673A54FF50[2]));
  AL_MAP_LUT4 #(
    .EQN("~(D@C@B@A)"),
    .INIT(16'h9669))
    al_000002673AAD7C70 (
    .a(al_000002673A8AA190[0]),
    .b(al_000002673A8AA190[1]),
    .c(al_000002673A8AA190[6]),
    .d(al_000002673A8AA190[7]),
    .o(al_000002673AA9E500));
  AL_MAP_LUT5 #(
    .EQN("~(E@D@C@B@A)"),
    .INIT(32'h69969669))
    al_000002673AAD90A0 (
    .a(al_000002673AA9E500),
    .b(al_000002673A8AA190[2]),
    .c(al_000002673A8AA190[3]),
    .d(al_000002673A8AA190[4]),
    .e(al_000002673A8AA190[5]),
    .o(al_000002673A8D2010));
  AL_MAP_LUT4 #(
    .EQN("(A*~(B)*~(C)*~(D)+~(A)*~(B)*~(C)*D+A*~(B)*~(C)*D+A*B*~(C)*D+~(A)*~(B)*C*D+A*~(B)*C*D+~(A)*B*C*D+A*B*C*D)"),
    .INIT(16'hfb02))
    al_000002673AAD8930 (
    .a(al_000002673A8A4BD0[0]),
    .b(al_000002673A8A4BD0[1]),
    .c(al_000002673A8A4BD0[2]),
    .d(al_000002673A8D3FB0),
    .o(al_000002673A8D4C10));
  AL_MAP_LUT4 #(
    .EQN("~(~A*~(B*~(D*~C)))"),
    .INIT(16'heaee))
    al_000002673AAD72E0 (
    .a(al_000002673A8D1E00),
    .b(al_000002673A8D4480),
    .c(al_000002673A8D5B30),
    .d(al_000002673A8D3FB0),
    .o(al_000002673A8D5BE0));
  AL_MAP_LUT4 #(
    .EQN("~(~(D*~C)*~(A)*~(B)+~(D*~C)*A*~(B)+~(~(D*~C))*A*B+~(D*~C)*A*B)"),
    .INIT(16'h4744))
    al_000002673AAD7D80 (
    .a(tx_en),
    .b(tx_rdy),
    .c(al_000002673A8D5B30),
    .d(al_000002673A8D3FB0),
    .o(al_000002673A8D4320));
  AL_MAP_LUT4 #(
    .EQN("(D*C*B*A)"),
    .INIT(16'h8000))
    al_000002673AAD73F0 (
    .a(al_000002673A830D30),
    .b(al_000002673A54CDE0[0]),
    .c(al_000002673A54CDE0[1]),
    .d(al_000002673A54CDE0[2]),
    .o(al_000002673A832EE0));
  AL_MAP_LUT4 #(
    .EQN("(A*B*~(C)*~(D)+~(A)*~(B)*~(C)*D+A*~(B)*~(C)*D+~(A)*B*~(C)*D+A*B*~(C)*D+~(A)*~(B)*C*D+~(A)*B*C*D)"),
    .INIT(16'h5f08))
    al_000002673AAD8A40 (
    .a(al_000002673A702530),
    .b(al_000002673A8C93D0),
    .c(al_000002673A55C970[0]),
    .d(rx_vld),
    .o(al_000002673A550340));
  AL_MAP_LUT3 #(
    .EQN("(~C*~B*A)"),
    .INIT(8'h02))
    al_000002673AAD6FB0 (
    .a(al_000002673A702530),
    .b(al_000002673A55C970[0]),
    .c(al_000002673A55C970[1]),
    .o(al_000002673AA9FBB0));
  AL_MAP_LUT2 #(
    .EQN("(~B*A)"),
    .INIT(4'h2))
    al_000002673AAD8E80 (
    .a(al_000002673A55C970[1]),
    .b(al_000002673A55C970[2]),
    .o(al_000002673AA9DAB0));
  AL_MAP_LUT4 #(
    .EQN("((D*~B)*~(A)*~(C)+(D*~B)*A*~(C)+~((D*~B))*A*C+(D*~B)*A*C)"),
    .INIT(16'ha3a0))
    al_000002673AAD9E70 (
    .a(al_000002673A550340),
    .b(al_000002673AA9FBB0),
    .c(al_000002673AA9DAB0),
    .d(rx_vld),
    .o(al_000002673A8CB2C0));
  AL_MAP_LUT4 #(
    .EQN("(D*C*B*A)"),
    .INIT(16'h8000))
    al_000002673AAD7500 (
    .a(al_000002673A55CB30[0]),
    .b(al_000002673A55CB30[1]),
    .c(al_000002673A55CB30[2]),
    .d(al_000002673A55CB30[3]),
    .o(al_000002673A8C95E0));
  AL_MAP_LUT2 #(
    .EQN("(B*A)"),
    .INIT(4'h8))
    al_000002673AAD8F90 (
    .a(al_000002673A8C95E0),
    .b(al_000002673A702530),
    .o(al_000002673A832AC0));
  AL_MAP_LUT4 #(
    .EQN("(D*~((~C*B))*~(A)+D*(~C*B)*~(A)+~(D)*(~C*B)*A+D*(~C*B)*A)"),
    .INIT(16'h5d08))
    al_000002673AAD7720 (
    .a(al_000002673AA9FBB0),
    .b(al_000002673A55C970[2]),
    .c(al_000002673A8CCA20),
    .d(al_000002673A8CC810),
    .o(al_000002673A8CB420));
  AL_MAP_LUT4 #(
    .EQN("(D*C*B*A)"),
    .INIT(16'h8000))
    al_000002673AAD7610 (
    .a(al_000002673AA9DAB0),
    .b(al_000002673A702530),
    .c(al_000002673A8C8350),
    .d(al_000002673A55C970[0]),
    .o(al_000002673AA9DB60));
  AL_MAP_LUT4 #(
    .EQN("(B*~((D@C))*~(A)+B*(D@C)*~(A)+~(B)*(D@C)*A+B*(D@C)*A)"),
    .INIT(16'h4ee4))
    al_000002673AAD8600 (
    .a(al_000002673AA9DB60),
    .b(al_000002673A8CCD90),
    .c(al_000002673A8CD470),
    .d(al_000002673A8CCA20),
    .o(al_000002673AAA03F0));
  AL_MAP_LUT3 #(
    .EQN("(A*~(~C*B))"),
    .INIT(8'ha2))
    al_000002673AAD7E90 (
    .a(al_000002673AAA03F0),
    .b(al_000002673AA9FBB0),
    .c(al_000002673A55C970[2]),
    .o(al_000002673A8CB840));
  AL_MAP_LUT4 #(
    .EQN("(D*~C*~B*A)"),
    .INIT(16'h0200))
    al_000002673AAD8710 (
    .a(al_000002673A8A87C0[0]),
    .b(al_000002673A8A87C0[1]),
    .c(al_000002673A8A87C0[2]),
    .d(al_000002673A8D4480),
    .o(al_000002673AA9DD70));
  AL_MAP_LUT4 #(
    .EQN("(~D*~C*~B*A)"),
    .INIT(16'h0002))
    al_000002673AAD93D0 (
    .a(al_000002673AA9DD70),
    .b(al_000002673A8A4BD0[0]),
    .c(al_000002673A8A4BD0[1]),
    .d(al_000002673A8A4BD0[2]),
    .o(al_000002673A8CD890));
  AL_MAP_LUT4 #(
    .EQN("(~D*~C*~B*~A)"),
    .INIT(16'h0001))
    al_000002673AAD8820 (
    .a(al_000002673A8A8980[0]),
    .b(al_000002673A8A8980[1]),
    .c(al_000002673A8A8980[2]),
    .d(al_000002673A8A8980[3]),
    .o(al_000002673A8A68B0[0]));
  AL_MAP_LUT2 #(
    .EQN("(B*A)"),
    .INIT(4'h8))
    al_000002673AAD8D70 (
    .a(al_000002673A702AB0),
    .b(al_000002673A8A4BD0[0]),
    .o(al_000002673AA9F210));
  AL_MAP_LUT4 #(
    .EQN("~(~D*C*B*A)"),
    .INIT(16'hff7f))
    al_000002673AAD91B0 (
    .a(al_000002673A8A68B0[0]),
    .b(al_000002673AA9F210),
    .c(al_000002673A8A4BD0[1]),
    .d(al_000002673A8A4BD0[2]),
    .o(al_000002673A8D2F30));
  AL_MAP_LUT5 #(
    .EQN("(~(A)*~(B)*~(C)*~(D)*~(E)+A*~(B)*~(C)*~(D)*~(E)+~(A)*B*~(C)*~(D)*~(E)+A*B*~(C)*~(D)*~(E)+~(A)*~(B)*C*~(D)*~(E)+A*~(B)*C*~(D)*~(E)+~(A)*B*C*~(D)*~(E)+A*B*C*~(D)*~(E)+~(A)*~(B)*~(C)*D*~(E)+A*~(B)*~(C)*D*~(E)+~(A)*B*~(C)*D*~(E)+A*B*~(C)*D*~(E)+~(A)*~(B)*C*D*~(E)+~(A)*B*C*D*~(E)+A*B*C*D*~(E)+~(A)*~(B)*~(C)*~(D)*E+A*~(B)*~(C)*~(D)*E+A*B*~(C)*~(D)*E+A*B*C*~(D)*E+~(A)*~(B)*~(C)*D*E+A*~(B)*~(C)*D*E+A*B*~(C)*D*E+A*~(B)*C*D*E+A*B*C*D*E)"),
    .INIT(32'hab8bdfff))
    al_000002673AACB8F0 (
    .a(al_000002673A702AB0),
    .b(al_000002673A8A4BD0[0]),
    .c(al_000002673A8A4BD0[1]),
    .d(al_000002673A8A8980[0]),
    .e(al_000002673A8A8980[1]),
    .o(al_000002673AA9F420));
  AL_MAP_LUT3 #(
    .EQN("(~C*~B*A)"),
    .INIT(8'h02))
    al_000002673AACBD30 (
    .a(al_000002673A702AB0),
    .b(al_000002673A8A4BD0[0]),
    .c(al_000002673A8A4BD0[1]),
    .o(al_000002673AA9F840));
  AL_MAP_LUT4 #(
    .EQN("(~A*~((D*~B))*~(C)+~A*(D*~B)*~(C)+~(~A)*(D*~B)*C+~A*(D*~B)*C)"),
    .INIT(16'h3505))
    al_000002673AACAD40 (
    .a(al_000002673AA9F420),
    .b(al_000002673AA9F840),
    .c(al_000002673A8A4BD0[2]),
    .d(al_000002673A8A8980[1]),
    .o(al_000002673A8A8670[1]));
  AL_MAP_LUT5 #(
    .EQN("(E*A*(C*~(B)*~(D)+C*B*~(D)+~(C)*B*D+C*B*D))"),
    .INIT(32'h88a00000))
    al_000002673AACAE50 (
    .a(al_000002673A702530),
    .b(al_000002673A8C8350),
    .c(al_000002673A8C93D0),
    .d(al_000002673A55C970[0]),
    .e(al_000002673A55C970[1]),
    .o(al_000002673AA5BBF0));
  AL_MAP_LUT4 #(
    .EQN("(~D*~(C*B*A))"),
    .INIT(16'h007f))
    al_000002673AACA4C0 (
    .a(al_000002673A702530),
    .b(al_000002673A8C8350),
    .c(al_000002673A55C970[0]),
    .d(al_000002673A55C970[1]),
    .o(al_000002673AA9F160));
  AL_MAP_LUT4 #(
    .EQN("(~D*C*~B*~A)"),
    .INIT(16'h0010))
    al_000002673AACDE20 (
    .a(al_000002673AA5BBF0),
    .b(al_000002673AA9F160),
    .c(rst_n),
    .d(al_000002673A55C970[2]),
    .o(al_000002673A8988B0[1]));
  AL_MAP_LUT2 #(
    .EQN("(~B*A)"),
    .INIT(4'h2))
    al_000002673AACB180 (
    .a(al_000002673A702530),
    .b(al_000002673A8CBF20),
    .o(al_000002673A8C9110));
  AL_MAP_LUT3 #(
    .EQN("(C*B*A)"),
    .INIT(8'h80))
    al_000002673AACC7D0 (
    .a(al_000002673A8C9110),
    .b(al_000002673A897F10[0]),
    .c(al_000002673A897F10[1]),
    .o(al_000002673AA9DC10));
  AL_MAP_LUT2 #(
    .EQN("(~B*~A)"),
    .INIT(4'h1))
    al_000002673AACDF30 (
    .a(al_000002673A55C970[0]),
    .b(al_000002673A55C970[1]),
    .o(al_000002673AA9E3A0));
  AL_MAP_LUT4 #(
    .EQN("(B*~(~D*~(C*A)))"),
    .INIT(16'hcc80))
    al_000002673AACB5C0 (
    .a(al_000002673AA9DC10),
    .b(al_000002673AA9E3A0),
    .c(al_000002673A897F10[2]),
    .d(al_000002673A897F10[3]),
    .o(al_000002673A76D950[3]));
  AL_MAP_LUT4 #(
    .EQN("(B*(A*~(C)*~(D)+~(A)*C*~(D)+A*~(C)*D+~(A)*C*D+A*C*D))"),
    .INIT(16'hc848))
    al_000002673AACCB00 (
    .a(al_000002673AA9DC10),
    .b(al_000002673AA9E3A0),
    .c(al_000002673A897F10[2]),
    .d(al_000002673A897F10[3]),
    .o(al_000002673A76D950[2]));
  AL_MAP_LUT4 #(
    .EQN("(D*C*B*A)"),
    .INIT(16'h8000))
    al_000002673AACDAF0 (
    .a(al_000002673A897F10[0]),
    .b(al_000002673A897F10[1]),
    .c(al_000002673A897F10[2]),
    .d(al_000002673A897F10[3]),
    .o(al_000002673AA9E5B0));
  AL_MAP_LUT5 #(
    .EQN("(B*~(~A*~(E@(D*C))))"),
    .INIT(32'h8cccc888))
    al_000002673AACD050 (
    .a(al_000002673AA9E5B0),
    .b(al_000002673AA9E3A0),
    .c(al_000002673A8C9110),
    .d(al_000002673A897F10[0]),
    .e(al_000002673A897F10[1]),
    .o(al_000002673A76D950[1]));
  AL_MAP_LUT4 #(
    .EQN("(B*~(~A*~(D@C)))"),
    .INIT(16'h8cc8))
    al_000002673AACA080 (
    .a(al_000002673AA9E5B0),
    .b(al_000002673AA9E3A0),
    .c(al_000002673A8C9110),
    .d(al_000002673A897F10[0]),
    .o(al_000002673A76D950[0]));
  AL_MAP_LUT2 #(
    .EQN("(~B*~A)"),
    .INIT(4'h1))
    al_000002673AACD6B0 (
    .a(al_000002673A8C95E0),
    .b(al_000002673AA9E5B0),
    .o(al_000002673AA9FFD0));
  AL_MAP_LUT3 #(
    .EQN("(C*B*A)"),
    .INIT(8'h80))
    al_000002673AACBE40 (
    .a(al_000002673A55B0F0[0]),
    .b(al_000002673A55B0F0[1]),
    .c(al_000002673A8CBF20),
    .o(al_000002673A830C80));
  AL_MAP_LUT4 #(
    .EQN("(A*(D@(C*B)))"),
    .INIT(16'h2a80))
    al_000002673AACC4A0 (
    .a(al_000002673AA9FFD0),
    .b(al_000002673A830C80),
    .c(al_000002673A55B0F0[2]),
    .d(al_000002673A55B0F0[3]),
    .o(al_000002673A772F10[3]));
  AL_MAP_LUT3 #(
    .EQN("(A*(C@B))"),
    .INIT(8'h28))
    al_000002673AACCF40 (
    .a(al_000002673AA9FFD0),
    .b(al_000002673A830C80),
    .c(al_000002673A55B0F0[2]),
    .o(al_000002673A772F10[2]));
  AL_MAP_LUT4 #(
    .EQN("(A*(C@(D*B)))"),
    .INIT(16'h28a0))
    al_000002673AACBF50 (
    .a(al_000002673AA9FFD0),
    .b(al_000002673A55B0F0[0]),
    .c(al_000002673A55B0F0[1]),
    .d(al_000002673A8CBF20),
    .o(al_000002673A772F10[1]));
  AL_MAP_LUT3 #(
    .EQN("(A*(C@B))"),
    .INIT(8'h28))
    al_000002673AACA190 (
    .a(al_000002673AA9FFD0),
    .b(al_000002673A55B0F0[0]),
    .c(al_000002673A8CBF20),
    .o(al_000002673A772F10[0]));
  AL_MAP_LUT4 #(
    .EQN("(~D*C*B*A)"),
    .INIT(16'h0080))
    al_000002673AACD160 (
    .a(al_000002673A8C95E0),
    .b(al_000002673AA9DAB0),
    .c(al_000002673A702530),
    .d(al_000002673A55C970[0]),
    .o(al_000002673A833D50));
  AL_MAP_LUT2 #(
    .EQN("(B*A)"),
    .INIT(4'h8))
    al_000002673AACD490 (
    .a(al_000002673A8A8980[0]),
    .b(al_000002673A8A8980[1]),
    .o(al_000002673A53A550));
  AL_MAP_LUT5 #(
    .EQN("(~(A)*~(B)*~(C)*~(D)*~(E)+A*~(B)*~(C)*~(D)*~(E)+~(A)*B*~(C)*~(D)*~(E)+A*B*~(C)*~(D)*~(E)+~(A)*~(B)*C*~(D)*~(E)+A*~(B)*C*~(D)*~(E)+~(A)*B*C*~(D)*~(E)+A*B*C*~(D)*~(E)+~(A)*~(B)*~(C)*D*~(E)+A*~(B)*~(C)*D*~(E)+~(A)*B*~(C)*D*~(E)+~(A)*~(B)*C*D*~(E)+A*~(B)*C*D*~(E)+~(A)*B*C*D*~(E)+A*B*C*D*~(E)+~(A)*~(B)*~(C)*~(D)*E+A*~(B)*~(C)*~(D)*E+~(A)*B*~(C)*~(D)*E+A*B*~(C)*~(D)*E+~(A)*B*C*~(D)*E+A*B*C*~(D)*E+A*B*~(C)*D*E+~(A)*B*C*D*E+A*B*C*D*E)"),
    .INIT(32'hc8cff7ff))
    al_000002673AACE040 (
    .a(al_000002673A53A550),
    .b(al_000002673A702AB0),
    .c(al_000002673A8A4BD0[0]),
    .d(al_000002673A8A4BD0[1]),
    .e(al_000002673A8A8980[2]),
    .o(al_000002673AAA0290));
  AL_MAP_LUT4 #(
    .EQN("(~A*~((D*~B))*~(C)+~A*(D*~B)*~(C)+~(~A)*(D*~B)*C+~A*(D*~B)*C)"),
    .INIT(16'h3505))
    al_000002673AACA2A0 (
    .a(al_000002673AAA0290),
    .b(al_000002673AA9F840),
    .c(al_000002673A8A4BD0[2]),
    .d(al_000002673A8A8980[2]),
    .o(al_000002673A8A8670[2]));
  AL_MAP_LUT2 #(
    .EQN("(B*A)"),
    .INIT(4'h8))
    al_000002673AACB290 (
    .a(al_000002673A53A550),
    .b(al_000002673A8A8980[2]),
    .o(al_000002673A53A340));
  AL_MAP_LUT5 #(
    .EQN("(~(A)*~(B)*~(C)*~(D)*~(E)+A*~(B)*~(C)*~(D)*~(E)+~(A)*B*~(C)*~(D)*~(E)+A*B*~(C)*~(D)*~(E)+~(A)*~(B)*C*~(D)*~(E)+A*~(B)*C*~(D)*~(E)+~(A)*B*C*~(D)*~(E)+A*B*C*~(D)*~(E)+~(A)*~(B)*~(C)*D*~(E)+A*~(B)*~(C)*D*~(E)+~(A)*B*~(C)*D*~(E)+~(A)*~(B)*C*D*~(E)+A*~(B)*C*D*~(E)+~(A)*B*C*D*~(E)+A*B*C*D*~(E)+~(A)*~(B)*~(C)*~(D)*E+A*~(B)*~(C)*~(D)*E+~(A)*B*~(C)*~(D)*E+A*B*~(C)*~(D)*E+~(A)*B*C*~(D)*E+A*B*C*~(D)*E+A*B*~(C)*D*E+~(A)*B*C*D*E+A*B*C*D*E)"),
    .INIT(32'hc8cff7ff))
    al_000002673AACA5D0 (
    .a(al_000002673A53A340),
    .b(al_000002673A702AB0),
    .c(al_000002673A8A4BD0[0]),
    .d(al_000002673A8A4BD0[1]),
    .e(al_000002673A8A8980[3]),
    .o(al_000002673AA9F580));
  AL_MAP_LUT4 #(
    .EQN("(~A*~((D*~B))*~(C)+~A*(D*~B)*~(C)+~(~A)*(D*~B)*C+~A*(D*~B)*C)"),
    .INIT(16'h3505))
    al_000002673AACCD20 (
    .a(al_000002673AA9F580),
    .b(al_000002673AA9F840),
    .c(al_000002673A8A4BD0[2]),
    .d(al_000002673A8A8980[3]),
    .o(al_000002673A8A8670[3]));
  AL_MAP_LUT3 #(
    .EQN("(C*B*A)"),
    .INIT(8'h80))
    al_000002673AACE150 (
    .a(al_000002673A8A8980[1]),
    .b(al_000002673A8A8980[2]),
    .c(al_000002673A8A8980[3]),
    .o(al_000002673AA9FF20));
  AL_MAP_LUT4 #(
    .EQN("(B*~(~C*~(D*A)))"),
    .INIT(16'hc8c0))
    al_000002673AACC060 (
    .a(al_000002673AA9FF20),
    .b(al_000002673A702AB0),
    .c(al_000002673A8A4BD0[0]),
    .d(al_000002673A8A8980[0]),
    .o(al_000002673AAA0080));
  AL_MAP_LUT5 #(
    .EQN("(A*~(~E*~D*~C*~B))"),
    .INIT(32'haaaaaaa8))
    al_000002673AACDC00 (
    .a(al_000002673A702AB0),
    .b(al_000002673A8A8980[0]),
    .c(al_000002673A8A8980[1]),
    .d(al_000002673A8A8980[2]),
    .e(al_000002673A8A8980[3]),
    .o(al_000002673AA9F0B0));
  AL_MAP_LUT5 #(
    .EQN("(A*~((~C*~B))*D*~(E)+A*(~C*~B)*D*~(E)+~(A)*(~C*~B)*~(D)*E+A*(~C*~B)*~(D)*E)"),
    .INIT(32'h0003aa00))
    al_000002673AACA900 (
    .a(al_000002673AAA0080),
    .b(al_000002673AA9F0B0),
    .c(al_000002673A8A4BD0[0]),
    .d(al_000002673A8A4BD0[1]),
    .e(al_000002673A8A4BD0[2]),
    .o(al_000002673A8A5F10[2]));
  AL_MAP_LUT4 #(
    .EQN("(C*~A*~(D*B))"),
    .INIT(16'h1050))
    al_000002673AACBC20 (
    .a(al_000002673AA9F0B0),
    .b(al_000002673A702AB0),
    .c(al_000002673A8A4BD0[0]),
    .d(al_000002673A8A4BD0[1]),
    .o(al_000002673AA9DA00));
  AL_MAP_LUT4 #(
    .EQN("(~C*~(~A*~(D*B)))"),
    .INIT(16'h0e0a))
    al_000002673AACE260 (
    .a(al_000002673AA9DA00),
    .b(al_000002673AA9F840),
    .c(al_000002673A8A4BD0[2]),
    .d(al_000002673A8D4480),
    .o(al_000002673A8A5F10[0]));
  AL_MAP_LUT4 #(
    .EQN("(~D*C*~(B*A))"),
    .INIT(16'h0070))
    al_000002673AACE370 (
    .a(al_000002673A702530),
    .b(al_000002673A8C8350),
    .c(al_000002673A55C970[0]),
    .d(al_000002673A55C970[2]),
    .o(al_000002673AA9DCC0));
  AL_MAP_LUT4 #(
    .EQN("(D*~(~B*~(C*A)))"),
    .INIT(16'hec00))
    al_000002673AACAC30 (
    .a(al_000002673AA9E5B0),
    .b(al_000002673AA9DCC0),
    .c(al_000002673AA9FBB0),
    .d(rst_n),
    .o(al_000002673A8988B0[0]));
  AL_MAP_LUT5 #(
    .EQN("(E*~D*C*B*A)"),
    .INIT(32'h00800000))
    al_000002673AACD5A0 (
    .a(al_000002673A8C95E0),
    .b(al_000002673AA9DAB0),
    .c(al_000002673A702530),
    .d(al_000002673A55C970[0]),
    .e(al_000002673A8CCA20),
    .o(al_000002673AAA01E0));
  AL_MAP_LUT4 #(
    .EQN("(~(~C*B)*(D@A))"),
    .INIT(16'h51a2))
    al_000002673AACBB10 (
    .a(al_000002673AAA01E0),
    .b(al_000002673AA9FBB0),
    .c(al_000002673A55C970[2]),
    .d(al_000002673A8CD470),
    .o(al_000002673A8CB6E0));
  AL_MAP_LUT5 #(
    .EQN("(~B*(~E*~((~D*~A))*~(C)+~E*(~D*~A)*~(C)+~(~E)*(~D*~A)*C+~E*(~D*~A)*C))"),
    .INIT(32'h00100313))
    al_000002673AACA3B0 (
    .a(al_000002673AA9FF20),
    .b(al_000002673A8A4BD0[0]),
    .c(al_000002673A8A8980[0]),
    .d(al_000002673A8AAAC0[0]),
    .e(txd),
    .o(al_000002673AA9E710));
  AL_MAP_LUT2 #(
    .EQN("(~B*A)"),
    .INIT(4'h2))
    al_000002673AACAF60 (
    .a(al_000002673A8A4BD0[0]),
    .b(al_000002673A8D5A80),
    .o(al_000002673AA9D8A0));
  AL_MAP_LUT5 #(
    .EQN("(~(A)*~(B)*~(C)*~(D)*~(E)+A*~(B)*~(C)*~(D)*~(E)+A*B*~(C)*~(D)*~(E)+~(A)*~(B)*C*~(D)*~(E)+A*~(B)*C*~(D)*~(E)+A*B*C*~(D)*~(E)+A*~(B)*~(C)*D*~(E)+A*B*~(C)*D*~(E)+~(A)*~(B)*C*D*~(E)+A*~(B)*C*D*~(E)+A*B*C*D*~(E)+A*~(B)*~(C)*D*E+A*B*~(C)*D*E+~(A)*~(B)*C*D*E+A*~(B)*C*D*E+A*B*C*D*E)"),
    .INIT(32'hba00babb))
    al_000002673AACC5B0 (
    .a(al_000002673AA9E710),
    .b(al_000002673AA9F0B0),
    .c(al_000002673AA9D8A0),
    .d(al_000002673A702AB0),
    .e(txd),
    .o(al_000002673AA9EDF0));
  AL_MAP_ADDER #(
    .ALUTYPE("ADD"))
    al_000002673A87D850 (
    .a(al_000002673A54D8D0[0]),
    .b(1'b1),
    .c(al_000002673A830B20),
    .o({al_000002673A82ECE0,al_000002673A54F770[0]}));
  AL_MAP_ADDER #(
    .ALUTYPE("ADD"))
    al_000002673A87D960 (
    .a(al_000002673A54D8D0[1]),
    .b(1'b0),
    .c(al_000002673A82ECE0),
    .o({al_000002673A82E290,al_000002673A54F770[1]}));
  AL_MAP_ADDER #(
    .ALUTYPE("ADD"))
    al_000002673A87EEA0 (
    .a(al_000002673A54D8D0[2]),
    .b(1'b0),
    .c(al_000002673A82E290),
    .o({al_000002673A82E4A0,al_000002673A54F770[2]}));
  AL_MAP_ADDER #(
    .ALUTYPE("ADD"))
    al_000002673A881C50 (
    .a(al_000002673A54D8D0[3]),
    .b(1'b0),
    .c(al_000002673A82E4A0),
    .o({al_000002673A830020,al_000002673A54F770[3]}));
  AL_MAP_ADDER #(
    .ALUTYPE("ADD"))
    al_000002673A87F720 (
    .a(al_000002673A54D8D0[4]),
    .b(1'b0),
    .c(al_000002673A830020),
    .o({al_000002673A82FB50,al_000002673A54F770[4]}));
  AL_MAP_ADDER #(
    .ALUTYPE("ADD"))
    al_000002673A87EC80 (
    .a(al_000002673A54D8D0[5]),
    .b(1'b0),
    .c(al_000002673A82FB50),
    .o({open_n0,al_000002673A54F770[5]}));
  AL_MAP_ADDER #(
    .ALUTYPE("ADD_CARRY"))
    al_000002673A87FD80 (
    .a(1'b0),
    .o({al_000002673A830B20,open_n3}));
  AL_DFF_X al_000002673A78F160 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A832EE0),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A702AB0));
  AL_DFF_0 al_000002673A78F490 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A830D30),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A702530));
  AL_MAP_ADDER #(
    .ALUTYPE("A_LE_B"))
    al_000002673A87F940 (
    .a(1'b0),
    .b(al_000002673A54D8D0[0]),
    .c(al_000002673A82E3F0),
    .o({al_000002673A82E600,open_n4}));
  AL_MAP_ADDER #(
    .ALUTYPE("A_LE_B"))
    al_000002673A87FFA0 (
    .a(1'b0),
    .b(al_000002673A54D8D0[1]),
    .c(al_000002673A82E600),
    .o({al_000002673A82E8C0,open_n5}));
  AL_MAP_ADDER #(
    .ALUTYPE("A_LE_B"))
    al_000002673A8800B0 (
    .a(1'b1),
    .b(al_000002673A54D8D0[2]),
    .c(al_000002673A82E8C0),
    .o({al_000002673A82FCB0,open_n6}));
  AL_MAP_ADDER #(
    .ALUTYPE("A_LE_B"))
    al_000002673A880930 (
    .a(1'b1),
    .b(al_000002673A54D8D0[3]),
    .c(al_000002673A82FCB0),
    .o({al_000002673A82FEC0,open_n7}));
  AL_MAP_ADDER #(
    .ALUTYPE("A_LE_B"))
    al_000002673A8801C0 (
    .a(1'b0),
    .b(al_000002673A54D8D0[4]),
    .c(al_000002673A82FEC0),
    .o({al_000002673A830390,open_n8}));
  AL_MAP_ADDER #(
    .ALUTYPE("A_LE_B"))
    al_000002673A880B50 (
    .a(1'b1),
    .b(al_000002673A54D8D0[5]),
    .c(al_000002673A830390),
    .o({al_000002673A831C50,open_n9}));
  AL_MAP_ADDER #(
    .ALUTYPE("A_LE_B_CARRY"))
    al_000002673A87F610 (
    .a(1'b1),
    .o({al_000002673A82E3F0,open_n12}));
  AL_MAP_ADDER #(
    .ALUTYPE("A_LE_B"))
    al_000002673A8814E0 (
    .a(1'b0),
    .b(1'b1),
    .c(al_000002673A831C50),
    .o({open_n13,al_000002673A830D30}));
  AL_DFF_X al_000002673A828380 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A54FF50[0]),
    .en(al_000002673A830D30),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A54CDE0[0]));
  AL_DFF_X al_000002673A826F50 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A54FF50[1]),
    .en(al_000002673A830D30),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A54CDE0[1]));
  AL_DFF_X al_000002673A8268F0 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A54FF50[2]),
    .en(al_000002673A830D30),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A54CDE0[2]));
  AL_DFF_0 al_000002673A8298C0 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A54F2A0[0]),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A54D8D0[0]));
  AL_DFF_0 al_000002673A827F40 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A54F2A0[1]),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A54D8D0[1]));
  AL_DFF_0 al_000002673A82A360 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A54F2A0[2]),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A54D8D0[2]));
  AL_DFF_0 al_000002673A826290 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A54F2A0[3]),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A54D8D0[3]));
  AL_DFF_0 al_000002673A827D20 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A54F2A0[4]),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A54D8D0[4]));
  AL_DFF_0 al_000002673A827060 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A54F2A0[5]),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A54D8D0[5]));
  AL_MAP_ADDER #(
    .ALUTYPE("ADD"))
    al_000002673A9338B0 (
    .a(al_000002673A55CB30[0]),
    .b(1'b1),
    .c(al_000002673A533280),
    .o({al_000002673A5335F0,al_000002673A897880[0]}));
  AL_MAP_ADDER #(
    .ALUTYPE("ADD"))
    al_000002673A933AD0 (
    .a(al_000002673A55CB30[1]),
    .b(1'b0),
    .c(al_000002673A5335F0),
    .o({al_000002673A535BC0,al_000002673A897880[1]}));
  AL_MAP_ADDER #(
    .ALUTYPE("ADD"))
    al_000002673A934CE0 (
    .a(al_000002673A55CB30[2]),
    .b(1'b0),
    .c(al_000002673A535BC0),
    .o({al_000002673A533120,al_000002673A897880[2]}));
  AL_MAP_ADDER #(
    .ALUTYPE("ADD"))
    al_000002673A936110 (
    .a(al_000002673A55CB30[3]),
    .b(1'b0),
    .c(al_000002673A533120),
    .o({al_000002673A533B70,al_000002673A897880[3]}));
  AL_MAP_ADDER #(
    .ALUTYPE("ADD"))
    al_000002673A934130 (
    .a(al_000002673A55CB30[4]),
    .b(1'b0),
    .c(al_000002673A533B70),
    .o({al_000002673A534880,al_000002673A897880[4]}));
  AL_MAP_ADDER #(
    .ALUTYPE("ADD"))
    al_000002673A936660 (
    .a(al_000002673A55CB30[5]),
    .b(1'b0),
    .c(al_000002673A534880),
    .o({al_000002673A533330,al_000002673A897880[5]}));
  AL_MAP_ADDER #(
    .ALUTYPE("ADD"))
    al_000002673A935DE0 (
    .a(al_000002673A55CB30[6]),
    .b(1'b0),
    .c(al_000002673A533330),
    .o({al_000002673A534510,al_000002673A897880[6]}));
  AL_MAP_ADDER #(
    .ALUTYPE("ADD"))
    al_000002673A934240 (
    .a(al_000002673A55CB30[7]),
    .b(1'b0),
    .c(al_000002673A534510),
    .o({open_n14,al_000002673A897880[7]}));
  AL_MAP_ADDER #(
    .ALUTYPE("ADD_CARRY"))
    al_000002673A934F00 (
    .a(1'b0),
    .o({al_000002673A533280,open_n17}));
  AL_MAP_ADDER #(
    .ALUTYPE("A_LE_B"))
    al_000002673A932BF0 (
    .a(1'b1),
    .b(al_000002673A55CB30[0]),
    .c(al_000002673A533CD0),
    .o({al_000002673A535380,open_n18}));
  AL_MAP_ADDER #(
    .ALUTYPE("A_LE_B"))
    al_000002673A936770 (
    .a(1'b1),
    .b(al_000002673A55CB30[1]),
    .c(al_000002673A535380),
    .o({al_000002673A533D80,open_n19}));
  AL_MAP_ADDER #(
    .ALUTYPE("A_LE_B"))
    al_000002673A9326A0 (
    .a(1'b1),
    .b(al_000002673A55CB30[2]),
    .c(al_000002673A533D80),
    .o({al_000002673A533EE0,open_n20}));
  AL_MAP_ADDER #(
    .ALUTYPE("A_LE_B"))
    al_000002673A939EB0 (
    .a(1'b1),
    .b(al_000002673A55CB30[3]),
    .c(al_000002673A533EE0),
    .o({al_000002673A534460,open_n21}));
  AL_MAP_ADDER #(
    .ALUTYPE("A_LE_B"))
    al_000002673A938EC0 (
    .a(1'b0),
    .b(al_000002673A55CB30[4]),
    .c(al_000002673A534460),
    .o({al_000002673A535430,open_n22}));
  AL_MAP_ADDER #(
    .ALUTYPE("A_LE_B"))
    al_000002673A936BB0 (
    .a(1'b0),
    .b(al_000002673A55CB30[5]),
    .c(al_000002673A535430),
    .o({al_000002673A534040,open_n23}));
  AL_MAP_ADDER #(
    .ALUTYPE("A_LE_B"))
    al_000002673A937760 (
    .a(1'b0),
    .b(al_000002673A55CB30[6]),
    .c(al_000002673A534040),
    .o({al_000002673A535590,open_n24}));
  AL_MAP_ADDER #(
    .ALUTYPE("A_LE_B"))
    al_000002673A937BA0 (
    .a(1'b0),
    .b(al_000002673A55CB30[7]),
    .c(al_000002673A535590),
    .o({al_000002673A5340F0,open_n25}));
  AL_MAP_ADDER #(
    .ALUTYPE("A_LE_B_CARRY"))
    al_000002673A935230 (
    .a(1'b1),
    .o({al_000002673A533CD0,open_n28}));
  AL_MAP_ADDER #(
    .ALUTYPE("A_LE_B"))
    al_000002673A938640 (
    .a(1'b0),
    .b(1'b1),
    .c(al_000002673A5340F0),
    .o({open_n29,al_000002673A8C8350}));
  AL_MAP_ADDER #(
    .ALUTYPE("A_LE_B"))
    al_000002673A93C710 (
    .a(1'b1),
    .b(al_000002673A55CB30[0]),
    .c(al_000002673A534A90),
    .o({al_000002673A534B40,open_n30}));
  AL_MAP_ADDER #(
    .ALUTYPE("A_LE_B"))
    al_000002673A93C2D0 (
    .a(1'b1),
    .b(al_000002673A55CB30[1]),
    .c(al_000002673A534B40),
    .o({al_000002673A5345C0,open_n31}));
  AL_MAP_ADDER #(
    .ALUTYPE("A_LE_B"))
    al_000002673A93D700 (
    .a(1'b1),
    .b(al_000002673A55CB30[2]),
    .c(al_000002673A5345C0),
    .o({al_000002673A534BF0,open_n32}));
  AL_MAP_ADDER #(
    .ALUTYPE("A_LE_B"))
    al_000002673A93B2E0 (
    .a(1'b1),
    .b(al_000002673A55CB30[3]),
    .c(al_000002673A534BF0),
    .o({al_000002673A534D50,open_n33}));
  AL_MAP_ADDER #(
    .ALUTYPE("A_LE_B"))
    al_000002673A93C600 (
    .a(1'b1),
    .b(al_000002673A55CB30[4]),
    .c(al_000002673A534D50),
    .o({al_000002673A535640,open_n34}));
  AL_MAP_ADDER #(
    .ALUTYPE("A_LE_B"))
    al_000002673A93C820 (
    .a(1'b1),
    .b(al_000002673A55CB30[5]),
    .c(al_000002673A535640),
    .o({al_000002673A5341A0,open_n35}));
  AL_MAP_ADDER #(
    .ALUTYPE("A_LE_B"))
    al_000002673A93AD90 (
    .a(1'b1),
    .b(al_000002673A55CB30[6]),
    .c(al_000002673A5341A0),
    .o({al_000002673A534250,open_n36}));
  AL_MAP_ADDER #(
    .ALUTYPE("A_LE_B"))
    al_000002673A93DE70 (
    .a(1'b0),
    .b(al_000002673A55CB30[7]),
    .c(al_000002673A534250),
    .o({al_000002673A534300,open_n37}));
  AL_MAP_ADDER #(
    .ALUTYPE("A_LE_B_CARRY"))
    al_000002673A937CB0 (
    .a(1'b1),
    .o({al_000002673A534A90,open_n40}));
  AL_MAP_ADDER #(
    .ALUTYPE("A_LE_B"))
    al_000002673A93C0B0 (
    .a(1'b0),
    .b(1'b1),
    .c(al_000002673A534300),
    .o({open_n41,al_000002673A8C93D0}));
  AL_DFF_X al_000002673A78C4C0 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A8CB840),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A8CCD90));
  AL_DFF_X al_000002673A878570 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A772F10[0]),
    .en(al_000002673A702530),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A55B0F0[0]));
  AL_DFF_X al_000002673A878AC0 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A772F10[1]),
    .en(al_000002673A702530),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A55B0F0[1]));
  AL_DFF_X al_000002673A87A110 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A772F10[2]),
    .en(al_000002673A702530),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A55B0F0[2]));
  AL_DFF_X al_000002673A876BF0 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A772F10[3]),
    .en(al_000002673A702530),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A55B0F0[3]));
  AL_DFF_X al_000002673A879BC0 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A76D950[0]),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A897F10[0]));
  AL_DFF_X al_000002673A879120 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A76D950[1]),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A897F10[1]));
  AL_DFF_X al_000002673A877470 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A76D950[2]),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A897F10[2]));
  AL_DFF_X al_000002673A878240 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A76D950[3]),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A897F10[3]));
  AL_DFF_X al_000002673A878BD0 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A8988B0[0]),
    .en(al_000002673A702530),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A55C970[0]));
  AL_DFF_X al_000002673A877F10 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A8988B0[1]),
    .en(al_000002673A702530),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A55C970[1]));
  AL_DFF_X al_000002673A878680 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A8988B0[2]),
    .en(al_000002673A702530),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A55C970[2]));
  AL_DFF_X al_000002673A879670 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A899100[0]),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A55CB30[0]));
  AL_DFF_X al_000002673A878130 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A899100[1]),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A55CB30[1]));
  AL_DFF_X al_000002673A879890 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A899100[2]),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A55CB30[2]));
  AL_DFF_X al_000002673A877AD0 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A899100[3]),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A55CB30[3]));
  AL_DFF_X al_000002673A879CD0 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A899100[4]),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A55CB30[4]));
  AL_DFF_X al_000002673A877580 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A899100[5]),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A55CB30[5]));
  AL_DFF_X al_000002673A878350 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A899100[6]),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A55CB30[6]));
  AL_DFF_X al_000002673A878DF0 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A899100[7]),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A55CB30[7]));
  AL_DFF_X al_000002673A878460 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(rx_data[1]),
    .en(al_000002673A833D50),
    .sr(1'b0),
    .ss(1'b0),
    .q(rx_data[0]));
  AL_DFF_X al_000002673A878790 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(rx_data[2]),
    .en(al_000002673A833D50),
    .sr(1'b0),
    .ss(1'b0),
    .q(rx_data[1]));
  AL_DFF_X al_000002673A878F00 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(rx_data[3]),
    .en(al_000002673A833D50),
    .sr(1'b0),
    .ss(1'b0),
    .q(rx_data[2]));
  AL_DFF_X al_000002673A879DE0 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(rx_data[4]),
    .en(al_000002673A833D50),
    .sr(1'b0),
    .ss(1'b0),
    .q(rx_data[3]));
  AL_DFF_X al_000002673A879EF0 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(rx_data[5]),
    .en(al_000002673A833D50),
    .sr(1'b0),
    .ss(1'b0),
    .q(rx_data[4]));
  AL_DFF_X al_000002673A87A220 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(rx_data[6]),
    .en(al_000002673A833D50),
    .sr(1'b0),
    .ss(1'b0),
    .q(rx_data[5]));
  AL_DFF_X al_000002673A87A550 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(rx_data[7]),
    .en(al_000002673A833D50),
    .sr(1'b0),
    .ss(1'b0),
    .q(rx_data[6]));
  AL_DFF_X al_000002673A87A440 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A8CCA20),
    .en(al_000002673A833D50),
    .sr(1'b0),
    .ss(1'b0),
    .q(rx_data[7]));
  AL_DFF_X al_000002673A938970 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A8CB6E0),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A8CD470));
  AL_DFF_X al_000002673A934350 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A8CB2C0),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(rx_vld));
  AL_DFF_X al_000002673A9327B0 (
    .ar(1'b0),
    .as(~rst_n),
    .clk(clk),
    .d(al_000002673A55B0F0[3]),
    .en(al_000002673A832AC0),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A8CCA20));
  AL_DFF_X al_000002673A934570 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A8CB790),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A8CBF20));
  AL_DFF_X al_000002673A9348A0 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(rxd),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A8CB790));
  AL_DFF_X al_000002673A935AB0 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A8CB420),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A8CC810));
  AL_DFF_X al_000002673A932D00 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(tx_data[0]),
    .en(al_000002673A8D1E00),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A8AA190[0]));
  AL_DFF_X al_000002673A9337A0 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(tx_data[1]),
    .en(al_000002673A8D1E00),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A8AA190[1]));
  AL_DFF_X al_000002673A9339C0 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(tx_data[2]),
    .en(al_000002673A8D1E00),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A8AA190[2]));
  AL_DFF_X al_000002673A935CD0 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(tx_data[3]),
    .en(al_000002673A8D1E00),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A8AA190[3]));
  AL_DFF_X al_000002673A934DF0 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(tx_data[4]),
    .en(al_000002673A8D1E00),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A8AA190[4]));
  AL_DFF_X al_000002673A933BE0 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(tx_data[5]),
    .en(al_000002673A8D1E00),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A8AA190[5]));
  AL_DFF_X al_000002673A936220 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(tx_data[6]),
    .en(al_000002673A8D1E00),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A8AA190[6]));
  AL_DFF_X al_000002673A935890 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(tx_data[7]),
    .en(al_000002673A8D1E00),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A8AA190[7]));
  AL_DFF_X al_000002673A935670 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A8A87C0[0]),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A8A4BD0[0]));
  AL_DFF_X al_000002673A933CF0 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A8A87C0[1]),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A8A4BD0[1]));
  AL_DFF_X al_000002673A935010 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A8A87C0[2]),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A8A4BD0[2]));
  AL_LATCH_X al_000002673A933580 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(al_000002673A8D2F30),
    .d(al_000002673A8A5F10[0]),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A8A87C0[0]));
  AL_LATCH_X al_000002673A936330 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(al_000002673A8D2F30),
    .d(al_000002673A8A5F10[1]),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A8A87C0[1]));
  AL_LATCH_X al_000002673A933E00 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(al_000002673A8D2F30),
    .d(al_000002673A8A5F10[2]),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A8A87C0[2]));
  AL_DFF_X al_000002673A933F10 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A8A8670[0]),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A8A8980[0]));
  AL_DFF_X al_000002673A934680 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A8A8670[1]),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A8A8980[1]));
  AL_DFF_X al_000002673A935340 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A8A8670[2]),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A8A8980[2]));
  AL_DFF_X al_000002673A935780 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A8A8670[3]),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A8A8980[3]));
  AL_DFF_X al_000002673A933360 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A8A86E0[0]),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A8AAAC0[0]));
  AL_DFF_X al_000002673A933250 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A8A86E0[1]),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A8AAAC0[1]));
  AL_DFF_X al_000002673A934460 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A8A86E0[2]),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A8AAAC0[2]));
  AL_DFF_X al_000002673A933140 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A8A86E0[3]),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A8AAAC0[3]));
  AL_DFF_X al_000002673A935120 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A8A86E0[4]),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A8AAAC0[4]));
  AL_DFF_X al_000002673A936000 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A8A86E0[5]),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A8AAAC0[5]));
  AL_DFF_X al_000002673A935560 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A8A86E0[6]),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A8AAAC0[6]));
  AL_DFF_X al_000002673A9328C0 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A8A86E0[7]),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A8AAAC0[7]));
  AL_DFF_X al_000002673A827390 (
    .ar(1'b0),
    .as(~rst_n),
    .clk(clk),
    .d(al_000002673A8D50E0),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(txd));
  AL_DFF_X al_000002673A8285A0 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A8D5BE0),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A8D4480));
  AL_DFF_X al_000002673A829F20 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A8D2010),
    .en(al_000002673A8CD890),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A8D5A80));
  AL_DFF_X al_000002673A82CBC0 (
    .ar(1'b0),
    .as(~rst_n),
    .clk(clk),
    .d(al_000002673A8D4320),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(tx_rdy));
  AL_DFF_X al_000002673A82CCD0 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A8D3FB0),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A8D5B30));
  AL_DFF_X al_000002673A881A30 (
    .ar(~rst_n),
    .as(1'b0),
    .clk(clk),
    .d(al_000002673A8D4C10),
    .en(1'b1),
    .sr(1'b0),
    .ss(1'b0),
    .q(al_000002673A8D3FB0));

endmodule 

module AL_DFF_X
  (
  ar,
  as,
  clk,
  d,
  en,
  sr,
  ss,
  q
  );

  input ar;
  input as;
  input clk;
  input d;
  input en;
  input sr;
  input ss;
  output q;

  wire al_000002673A7CF210;
  wire al_000002673A7CF6E0;
  wire al_000002673A7CF2C0;

  AL_MUX_release al_000002673A7C58E0 (
    .i0(q),
    .i1(d),
    .sel(en),
    .o(al_000002673A7CF210));
  AL_MUX_release al_000002673A7C5390 (
    .i0(al_000002673A7CF2C0),
    .i1(1'b0),
    .sel(sr),
    .o(al_000002673A7CF6E0));
  AL_DFF_release al_000002673A7C7590 (
    .clk(clk),
    .d(al_000002673A7CF6E0),
    .reset(ar),
    .set(as),
    .q(q));
  AL_MUX_release al_000002673A7C59F0 (
    .i0(al_000002673A7CF210),
    .i1(1'b1),
    .sel(ss),
    .o(al_000002673A7CF2C0));

endmodule 

module AL_DFF_0
  (
  ar,
  as,
  clk,
  d,
  en,
  sr,
  ss,
  q
  );

  input ar;
  input as;
  input clk;
  input d;
  input en;
  input sr;
  input ss;
  output q;

  wire al_000002673A476140;
  wire al_000002673A476820;
  wire al_000002673A4762A0;

  AL_MUX_release al_000002673A7C4180 (
    .i0(q),
    .i1(d),
    .sel(en),
    .o(al_000002673A476140));
  AL_MUX_release al_000002673A7C7150 (
    .i0(al_000002673A4762A0),
    .i1(1'b0),
    .sel(sr),
    .o(al_000002673A476820));
  AL_DFF_release #(
    .INI(1'b0))
    al_000002673A7C67C0 (
    .clk(clk),
    .d(al_000002673A476820),
    .reset(ar),
    .set(as),
    .q(q));
  AL_MUX_release al_000002673A7C54A0 (
    .i0(al_000002673A476140),
    .i1(1'b1),
    .sel(ss),
    .o(al_000002673A4762A0));

endmodule 

module AL_LATCH_X
  (
  ar,
  as,
  clk,
  d,
  en,
  sr,
  ss,
  q
  );

  input ar;
  input as;
  input clk;
  input d;
  input en;
  input sr;
  input ss;
  output q;

  wire al_000002673A536820;
  wire al_000002673A5378A0;
  wire al_000002673A538450;

  AL_MUX_release al_000002673A7C56C0 (
    .i0(q),
    .i1(d),
    .sel(en),
    .o(al_000002673A536820));
  AL_MUX_release al_000002673A7C57D0 (
    .i0(al_000002673A538450),
    .i1(1'b0),
    .sel(sr),
    .o(al_000002673A5378A0));
  AL_LATCH_release al_000002673A7C5E30 (
    .clk(clk),
    .d(al_000002673A5378A0),
    .reset(ar),
    .set(as),
    .q(q));
  AL_MUX_release al_000002673A7C6F30 (
    .i0(al_000002673A536820),
    .i1(1'b1),
    .sel(ss),
    .o(al_000002673A538450));

endmodule 

module AL_MUX_release
  (
  input i0,
  input i1,
  input sel,
  output o
  );

  wire not_sel, sel_i0, sel_i1;
  not u0 (not_sel, sel);
  and u1 (sel_i1, sel, i1);
  and u2 (sel_i0, not_sel, i0);
  or u3 (o, sel_i1, sel_i0);

endmodule

module AL_DFF_release
  (
  input reset,
  input set,
  input clk,
  input d,
  output reg q
  );

  parameter INI = 1'b0;

  always @(posedge reset or posedge set or posedge clk)
  begin
    if (reset)
      q <= 1'b0;
    else if (set)
      q <= 1'b1;
    else
      q <= d;
  end

endmodule

module AL_LATCH_release
  (
  input reset,
  input set,
  input clk,
  input d,
  output reg q
  );

  parameter INI = 1'b0;

  always @(reset or set or clk or d)
  begin
    if (reset)
      q <= 1'b0;
    else if (set)
      q <= 1'b1;
    else if (clk)
      q <= d;
  end

endmodule

